---
- name: Get current timedatectl settings
  command: timedatectl show
  register: current_timedatectl
  changed_when: false

- name: Get valid timezones
  command: timedatectl list-timezones --no-pager
  register: valid_timezones
  changed_when: false

- name: Check user timezone against valid timezones
  fail:
    msg: "{{ timedatectl.timezone }} is not a valid timezonectl option."
  when: timedatectl.timezone not in valid_timezones.stdout

- name: Set timezone
  shell: "timedatectl set-timezone {{ timedatectl.timezone }}; timedatectl show"
  register: updated_timedatectl
  changed_when: "'Timezone={{ timedatectl.timezone }}' in updated_timedatectl.stdout"
  when: "'Timezone={{ timedatectl.timezone }}' not in current_timedatectl.stdout"