- name: Set umask via /etc/profile
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/profile
    regexp: '^umask.*$'
    line: umask 027
    owner: root
    group: root
    mode: 0644

- name: Set umask via /etc/profile.d/umask.sh
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/profile.d/umask.sh
    line: umask 027
    state: present
    create: yes
    owner: root
    group: root
    mode: 0644

- name: Set coredump via /etc/profile.d/coredump.sh
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/profile.d/coredump.sh
    line: ulimit -c 0
    state: present
    create: yes
    owner: root
    group: root
    mode: 0644