---
- name: Set umask via /etc/profile.d/umask.sh
  become: true
  lineinfile:
    dest: /etc/profile.d/umask.sh
    line: umask 027
    state: present
    create: yes
    owner: root
    group: root
    mode: 0644