# User
pacman_helper_user_uid: 1002

# Configuration
pacman_parallel_downloads: 6

# Mirrorlist
pacman_mirrorlist_country: US
pacman_mirrorlist_protocol: https
pacman_mirrorlist_ip_version: 4
pacman_mirrorlist_status: 'on'