---
- hosts: all

  vars_files:
    - "defaults/{{ lgsm_server }}.yml"

  tasks:
    - name: "Restart {{ lgsm_server }}"
      include_tasks: tasks/restart_server.yml

    - name: Give LGSM 45 seconds to restart
      pause:
        seconds: 45

    - name: "Set AutoParty to true"
      include_tasks: tasks/set_autoparty_true.yml