---
- hosts: all

  vars_files:
    - defaults/main.yml

  tasks:
    - name: "Restart {{ lgsm_server }}"
      include_tasks: tasks/restart_server.yml

    - name: Give LGSM 10 seconds to restart
      pause:
        minutes: 1

    - name: "Set AutoParty to true"
      include_tasks: tasks/set_autoparty_true.yml