---
# Packages
mattermost_packages:
  - mattermost
  # - python-psycopg2 # Not sure anymore if this is actually needed

# Users
mattermost_user: mattermost
mattermost_user_uid: 1600

# Groups
mattermost_group: mattermost
mattermost_group_gid: 1600

# Directories
mattermost_config_dir: /etc/webapps/mattermost
mattermost_data_dir: /var/lib/mattermost

# Databases
mattermost_db: mattermost