# SSL
mattermost_ssl: enabled

# User
mattermost_user_uid: 1600
mattermost_group_gid: 1600

# Database
mattermost_database: mattermost
mattermost_database_type: postgres
mattermost_database_host: 'postgres.{{ ansible_domain | default("example.com") }}'
mattermost_database_host_type: remote
mattermost_database_port: 5432
mattermost_database_ssl_mode: verify-full
mattermost_database_timeout: 10
mattermost_database_binary_parameters: 'yes'
mattermost_database_admin_user: '{{ postgresql_user | default("postgres") }}'
mattermost_database_user: '{{ mattermost_user }}'
mattermost_database_password: '{{ lookup("ansible.builtin.password", "/dev/null chars=ascii_lowercase,ascii_uppercase,digits length=20", seed=inventory_hostname) }}'