# User
mattermost_ssl_group: '{{ ssl_user_group | default("ssl-cert") }}'
mattermost_user_uid: 1600
mattermost_group_gid: 1600

# Database
mattermost_database: mattermost
mattermost_database_host: postgres
mattermost_database_admin_user: '{{ postgresql_user | default("postgres") }}'
mattermost_database_user: '{{ mattermost_user }}'
mattermost_database_password: supersecure
mattermost_database_no_log: yes