# Packages
certbot_binary: certbot
certbot_packages:
  - certbot
  - certbot-dns-cloudflare

# User
certbot_user: certbot
certbot_user_shell: /bin/bash
certbot_group: certbot

# Directories
certbot_certificate_dir: '{{ certbot_config_live_dir }}/{{ certbot_domain }}'
certbot_config_dir: /etc/letsencrypt
certbot_config_archive_dir: '{{ certbot_config_dir }}/archive'
certbot_config_live_dir: '{{ certbot_config_dir }}/live'
certbot_log_dir: /var/log/letsencrypt
certbot_work_dir: /var/lib/letsencrypt

# Files
certbot_config_file: cli.ini
certbot_cert_file: fullchain.pem
certbot_key_file: privkey.pem

# Commands
certbot_new_command: certonly