---
- name: Install `python-cryptography` via pacman
  become: yes
  community.general.pacman:
    name: python-cryptography
    state: latest

- name: Create mediacenter group
  become: yes
  ansible.builtin.group:
    name: mediacenter
    state: present

- name: Generate OpenSSL private key
  become: yes
  community.crypto.openssl_privatekey:
    group: mediacenter
    mode: '0640'
    path: '{{ssl.path.private}}'

- name: Create certificate signing request (CSR)
  become: yes
  community.crypto.openssl_csr_pipe:
    common_name: '{{ssl.name}}'
    privatekey_path: '{{ssl.path.private}}'
  changed_when: false
  register: csr

- name: Create self-signed certificate from CSR
  become: yes
  community.crypto.x509_certificate:
    csr_content: "{{ csr.csr }}"
    group: mediacenter
    path: '{{ssl.path.cert}}'
    privatekey_path: '{{ssl.path.private}}'
    provider: selfsigned