---
- hosts: all
  
  tasks:
    - name: "Update {{ lgsm_server }} server to latest"
      command: "/home/{{ lgsm_server }}/{{ lgsm_server }} update"
      register: update_server
      changed_when: "'No update available' not in update_server.stdout"
