---
- name: Install aptitude
  apt:
    name: aptitude
    state: latest
    install_recommends: no

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
    update_cache: yes
    cache_valid_time: 3600
    install_recommends: no

- name: Install preferred system packages via APT
  apt:
    name: "{{ apt.install }}"
    state: latest
    install_recommends: no
  when: apt.install is defined

- name: Remove unneccessary default packages
  apt:
    name: "{{ apt.remove }}"
    state: absent
    autoclean: yes
    autoremove: yes
  ignore_errors: true
  when: apt.remove is defined

- name: Purge unused packages via aptitude
  apt:
    purge: 'yes'