---
- name: Generate OpenSSL private key
  become: yes
  community.crypto.openssl_privatekey:
    group: "{{ ssl_user_group }}"
    mode: "{{ ssl_mode }}"
    path: '{{ ssl_key_dir }}/{{ ssl_name }}.key'

- name: Create certificate signing request (CSR)
  become: yes
  community.crypto.openssl_csr_pipe:
    common_name: '{{ssl_name}}'
    privatekey_path: '{{ ssl_key_dir }}/{{ ssl_name }}.key'
  changed_when: false
  register: csr

- name: Create self-signed certificate from CSR
  become: yes
  community.crypto.x509_certificate:
    csr_content: "{{ csr.csr }}"
    group: "{{ ssl_user_group }}"
    mode: "{{ ssl_mode }}"
    path: '{{ ssl_cert_dir }}/{{ ssl_name }}.crt'
    privatekey_path: '{{ ssl_key_dir }}/{{ ssl_name }}.key'
    provider: selfsigned