---
- name: Update system packages & install Teleport
  hosts: archlinux
  roles:
    - pacman

- name: Configure basic host & network settings
  hosts: archlinux
  roles:
    - resolvconf
    - hosts

- name: Harden system configuration to be security-forward
  hosts: archlinux
  roles:
    - sshd
    - profile
    - logindefs
    - coredump
    - modprobe
    - sysctl
    - privileges

- name: Configure additional packages for additional security
  hosts: archlinux
  roles:
    - libpwquality
    - logrotate
    - apparmor
    - rkhunter
    - lynis

- name: Configure media center storage & delivery
  hosts: archlinux:&mediacenter
  roles:
    - nfs
    - nzbget
    - prowlarr
    - sonarr
    - radarr
    - readarr
    - lidarr
    - plex