---
- name: Install `sonarr` using yay
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    name: sonarr
    state: latest
    use: yay

- name: Add sonarr user to nzbget group
  become: true
  ansible.builtin.user:
    name: sonarr
    groups: nzbget
    append: yes

- name: Enable sonarr service using systemd
  become: true
  systemd:
    enabled: yes
    name: sonarr
    state: started