---
nzbget:
  config:
    - line: "MainDir={{nfs.path.downloads.dir}}"
      regex: '^MainDir='
    - line: CertStore=/etc/ssl/certs/ca-certificates.crt
      regex: '^CertStore='
    - line: CertCheck=yes
      regex: '^CertCheck='
    - line: FormAuth=yes
      regex: '^FormAuth='
    - line: SecureControl=yes
      regex: '^SecureControl='
    - line: "SecureCert=/etc/ssl/certs/nzbget.{{ ansible_dns.search[0] | default('example.com') }}.crt"
      regex: '^SecureCert='
    - line: "SecureKey=/etc/ssl/private/nzbget.{{ ansible_dns.search[0] | default('example.com') }}.key"
      regex: '^SecureKey='
    - line: UMask=002
      regex: '^UMask='
    - line: AppendCategoryDir=yes
      regex: '^AppendCategoryDir='
    - line: DirectRename=yes
      regex: '^DirectRename='
    - line: DirectUnpack=yes
      regex: '^DirectUnpack='
    - line: ReorderFiles=yes
      regex: '^ReorderFiles='
  dependencies:
    - p7zip
    - par2cmdline
    - unrar
    - unzip
  user:
    name: nzbget
    group: nzbget
    uid: 1003
    gid: 1003
  path:
    config: /var/lib/nzbget/.nzbget
    cert: /etc/ssl/certs
    private: /etc/ssl/private
  web:
    subdomain: nzbget
    domain: "{{ ansible_dns.search[0] | default('example.com') }}"
