- name: Check if certificate exists
  become: true
  ansible.builtin.stat:
    path: '{{ certbot_config_live_dir }}/{{ certbot_domain }}/{{ certbot_cert_file }}'
  register: __certbot_cert

- name: Generate certificate
  become: true
  become_user: '{{ certbot_user }}'
  ansible.builtin.command: '{{ certbot_binary }} {{ certbot_new_command }}'
  when: not __certbot_cert.stat.exists
  register: __certbot_cert_generate
  # changed_when: "'Updated' in __certbot_cert_generate.stdout"
  failed_when: "'Error' in __certbot_cert_generate.stdout"