- name: Check if certificate exists
  become: true
  ansible.builtin.stat:
    path: '{{ certbot_certificate_dir }}/{{ certbot_cert_file }}'
  register: __certbot_cert

- name: Generate certificate
  become: true
  become_user: '{{ certbot_user }}'
  ansible.builtin.command: '{{ certbot_binary | quote }} {{ certbot_new_command | quote }}'
  when: not __certbot_cert.stat.exists
  register: __certbot_cert_generate
  changed_when: "'Successfully received certificate' in __certbot_cert_generate.stdout"
  failed_when: "'Error' in __certbot_cert_generate.stderr or 'fail' in __certbot_cert_generate.stderr"