- name: Create dns configuration
  become: true
  ansible.builtin.lineinfile:
    dest: '{{ certbot_config_dir }}/{{ certbot_dns_credentials_file }}'
    regex: '^dns_cloudflare_api_token = .*'
    line: 'dns_cloudflare_api_token = {{ certbot_dns_api_token }}'
    state: present
    create: true
    owner: '{{ certbot_user }}'
    group: '{{ certbot_group }}'
    mode: '{{ certbot_dns_credentials_file_mode }}'
  no_log: '{{ certbot_dns_credentials_no_log }}'

- name: Copy config template
  become: true
  ansible.builtin.template:
    src: cli.ini.j2
    dest: '{{ certbot_config_dir }}/{{ certbot_config_file }}'
    owner: '{{ certbot_user }}'
    group: '{{ certbot_group }}'
    mode: '{{ certbot_config_file_mode }}'