- name: Variables
  include_tasks: variables.yml

- name: Install
  include_tasks: install.yml

- name: Initialize
  include_tasks: initialize.yml

- name: Configure
  include_tasks: configure.yml

- name: Certificate
  include_tasks: certificate.yml