---
# HOST
host:
  domain: mydomain.com
  email: admin@mydomain.com
  nameservers:
    - 1.1.1.1
    - 1.0.0.1

# NETWORK
network:
  domain: "{{ vault.host.domain }}"
  hostname: "{{ inventory_hostname }}"
  ip: "{{ ansible_host }}"
  nameservers: "{{ vault.host.nameservers }}"

# POSTFIX
postfix_disable_vrfy_command: "yes"
postfix_inet_interfaces: "loopback-only"
postfix_smtp_tls_loglevel: "1"
postfix_smtpd_banner: "$myhostname ESMTP"
postfix_smtpd_client_restrictions: "permit_mynetworks,reject"
postfix_smtpd_helo_required: "yes"