---
# HOST
host:
  domain: mydomain.com
  email: admin@mydomain.com
  nameservers:
    - 1.1.1.1
    - 1.0.0.1

# FAIL2BAN
fail2ban_backend: "auto"
fail2ban_bantime: "10m"
fail2ban_destemail: "{{ vault.host.email }}"
fail2ban_findtime: "10m"
fail2ban_logencoding: "auto"
fail2ban_maxretry: "5"
fail2ban_mta: "sendmail"
fail2ban_protocol: "tcp"
fail2ban_sender: "fail2ban.{{ network.hostname }}@{{ network.domain }}"
fail2ban_usedns: "warn"

# LOGIN DEFS
logindefs:
  conf:
    CHFN_RESTRICT: rwh
    DEFAULT_HOME: "no"
    ENCRYPT_METHOD: SHA512
    ENV_PATH: "PATH=/usr/local/bin:/usr/bin:/bin"
    ENV_SUPATH: "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    ERASECHAR: 0177
    FAILLOG_ENAB: "yes"
    FTMP_FILE: /var/log/btmp
    GID_MAX: 60000
    GID_MIN: 1000
    HUSHLOGIN_FILE: .hushlogin
    KILLCHAR: 025
    LOG_OK_LOGINS: "yes"
    LOG_UNKFAIL_ENAB: "no"
    LOGIN_RETRIES: 5
    LOGIN_TIMEOUT: 30
    MAIL_DIR: /var/mail
    PASS_MAX_DAYS: 365
    PASS_MIN_DAYS: 1
    PASS_WARN_AGE: 7
    SHA_CRYPT_MAX_ROUNDS: 65536
    SHA_CRYPT_MIN_ROUNDS: 10000
    SU_NAME: su
    SYSLOG_SG_ENAB: "yes"
    SYSLOG_SU_ENAB: "yes"
    TTYGROUP: tty
    TTYPERM: 0600
    UID_MAX: 60000
    UID_MIN: 1000
    UMASK: 077
    USERGROUPS_ENAB: "no"

# NETWORK
network:
  domain: "{{ vault.host.domain }}"
  hostname: "{{ inventory_hostname }}"
  ip: "{{ ansible_host }}"
  nameservers: "{{ vault.host.nameservers }}"

# POSTFIX
postfix_disable_vrfy_command: "yes"
postfix_inet_interfaces: "loopback-only"
postfix_smtp_tls_loglevel: "1"
postfix_smtpd_banner: "$myhostname ESMTP"
postfix_smtpd_client_restrictions: "permit_mynetworks,reject"
postfix_smtpd_helo_required: "yes"

# USERS
users:
  blacklist:
    - games
    - gnats
    - irc
    - list
    - news
    - sync
    - uucp
  cracklib:
    dcredit: -2
    difok: 3
    lcredit: -2
    minlen: 16
    ocredit: -1
    retry: 3
    ucredit: -1

# RKHUNTER
rkhunter_ALLOW_SSH_PROT_V1: "0"
rkhunter_ALLOW_SSH_ROOT_USER: "no"
rkhunter_APT_AUTOGEN: "true"
rkhunter_CRON_DAILY_RUN: "true"
rkhunter_CRON_DB_UPDATE: "true"
rkhunter_DB_UPDATE_EMAIL: "false"
rkhunter_MIRRORS_MODE: "0"
rkhunter_NICE: "0"
rkhunter_REPORT_EMAIL: "{{ vault.host.email }}"
rkhunter_RUN_CHECK_ON_BATTERY: "false"
rkhunter_UPDATE_MIRRORS: "1"

# SSHD
sshd_AcceptEnv: "LANG LC_*"
sshd_AddressFamily: "inet"
sshd_AllowAgentForwarding: "no"
sshd_AllowTcpForwarding: "no"
sshd_AuthorizedKeysCommand: "none"
sshd_AuthorizedKeysCommandUser: "nobody"
sshd_AuthorizedKeysFile: ".ssh/authorized_keys"
sshd_AuthorizedPrincipalsFile: "none"
sshd_Banner: "/etc/issue.net"
sshd_ChallengeResponseAuthentication: "no"
sshd_ChrootDirectory: "none"
sshd_Ciphers: "chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com"
sshd_ClientAliveCountMax: "2"
sshd_ClientAliveInterval: "300"
sshd_Compression: "no"
sshd_GatewayPorts: "no"
sshd_GSSAPIAuthentication: "no"
sshd_GSSAPICleanupCredentials: "yes"
sshd_GSSAPIKeyExchange: "no"
sshd_GSSAPIStrictAcceptorCheck: "yes"
sshd_HostbasedAuthentication: "no"
sshd_HostKey: "/etc/ssh/ssh_host_ecdsa_key"
sshd_HostKey2: "/etc/ssh/ssh_host_ed25519_key"
sshd_HostKey3: "/etc/ssh/ssh_host_rsa_key"
sshd_HostKeyAlgorithms: "ssh-ed25519,ssh-ed25519-cert-v01@openssh.com,sk-ssh-ed25519@openssh.com,sk-ssh-ed25519-cert-v01@openssh.com,rsa-sha2-256,rsa-sha2-512,rsa-sha2-256-cert-v01@openssh.com,rsa-sha2-512-cert-v01@openssh.com"
sshd_IgnoreRhosts: "yes"
sshd_IgnoreUserKnownHosts: "yes"
sshd_KerberosAuthentication: "no"
sshd_KerberosGetAFSToken: "no"
sshd_KerberosOrLocalPasswd: "yes"
sshd_KerberosTicketCleanup: "yes"
sshd_KexAlgorithms: "curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256"
sshd_ListenAddress: "0.0.0.0"
sshd_LoginGraceTime: "30s"
sshd_LogLevel: "VERBOSE"
sshd_MACs: "umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com"
sshd_MaxAuthTries: "3"
sshd_MaxSessions: "2"
sshd_MaxStartups: "3"
sshd_PasswordAuthentication: "no"
sshd_PermitEmptyPasswords: "no"
sshd_PermitRootLogin: "no"
sshd_PermitTTY: "yes"
sshd_PermitTunnel: "no"
sshd_PermitUserEnvironment: "no"
sshd_PidFile: "/var/run/sshd.pid"
sshd_Port: "22"
sshd_PrintLastLog: "yes"
sshd_PrintMotd: "no"
sshd_Protocol: "2"
sshd_PubkeyAuthentication: "yes"
sshd_RekeyLimit: "1G 1300"
sshd_StrictModes: "yes"
sshd_Subsystem: "sftp /usr/lib/openssh/sftp-server"
sshd_SyslogFacility: "AUTHPRIV"
sshd_TCPKeepAlive: "no"
sshd_UseDNS: "no"
sshd_UsePAM: "yes"
sshd_UsePrivilegeSeparation: "sandbox"
sshd_VersionAddendum: "none"
sshd_X11DisplayOffset: "10"
sshd_X11Forwarding: "no"
sshd_X11UseLocalhost: "yes"