---
- name: Install aptitude
  apt:
    name: aptitude
    state: latest
    install_recommends: no

- name: Upgrade packages to latest
  apt:
    name: "*"
    state: latest
    update_cache: yes
    cache_valid_time: 3600
    install_recommends: no

- name: Install desired packages
  apt:
    name: "{{ apt.install }}"
    state: latest
    install_recommends: no
  when: apt.install is defined

- name: Remove desired packages
  apt:
    name: "{{ apt.remove }}"
    state: absent
  ignore_errors: true
  when: apt.remove is defined

- name: Autoclean & autoremove packages
  apt:
    autoclean: yes
    autoremove: yes

- name: Purge packages
  apt:
    purge: yes