---
- name: Apply coredump config via sysctl
  become: true
  sysctl:
    name: kernel.core_pattern
    value: /dev/null
    state: present
    sysctl_set: yes
    reload: yes

- name: Create systemd directory
  become: true
  file:
    path: /etc/systemd/coredump.conf.d
    state: directory
    owner: root
    group: root
    mode: 0644

- name: Copy coredump conf for systemd
  become: true
  template:
    src: templates/etc/systemd/coredump.conf.d/50-coredump.conf.j2
    dest: /etc/systemd/coredump.conf.d/50-coredump.conf
    owner: root
    group: root
    mode: 0644
  notify: Reload systemd

- name: Create PAM directory
  become: true
  file:
    path: /etc/security/limits.d/
    state: directory
    owner: root
    group: root
    mode: 0644

- name: Copy coredump conf for PAM
  become: true
  lineinfile:
    dest: /etc/security/limits.d/50-coredump.conf
    line: "* hard core 0"
    regexp: '(^#)?\*\s+hard\s+core\s+[0-9]+'
    state: present
    create: true
    owner: root
    group: root
    mode: 0644