---
# Packages
postgresql_binary: postgresql
postgresql_packages:
  - postgresql
  - python-psycopg

# Users
postgresql_user: postgres

# Groups
postgresql_group: postgres

# Directories
postgresql_bin_dir: /usr/bin
postgresql_config_dir: /var/lib/postgres/data
postgresql_data_dir: /var/lib/postgres/data

# Global Configuration
postgresql_listen_addresses:
  - localhost
  - "{{ ansible_host }}"
postgresql_unix_socket_dir:
  - /run/postgresql
postgresql_unix_socket_dir_mode: 0755
postgresql_global_config:
  - option: db_user_namespace
    value: "off"
  - option: listen_addresses
    value: '{{ postgresql_listen_addresses | join(",") }}'
  - option: log_destination
    value: stderr
  - option: logging_collector
    value: "off"
  - option: log_directory
    value: log
  - option: port
    value: 5432
  - option: password_encryption
    value: "{{ postgresql_auth_method }}"
  - option: ssl
    value: "on"
  - option: ssl_cert_file
    value: "{{ ssl_cert_dir }}/{{ ssl_name }}.crt"
  - option: ssl_key_file
    value: "{{ ssl_key_dir }}/{{ ssl_name }}.key"
  - option: ssl_ciphers
    value: "HIGH:MEDIUM:+3DES:!aNULL"
  - option: ssl_prefer_server_ciphers
    value: "on"
  - option: ssl_ecdh_curve
    value: "secp521r1"
  - option: ssl_min_protocol_version
    value: TLSv1.2
  - option: stats_temp_directory
    value: /run/postgresql
  - option: unix_socket_directories
    value: '{{ postgresql_unix_socket_dir | join(",") }}'
  - option: unix_socket_permissions
    value: 0770

# Host-based Authentication
postgresql_auth_method: scram-sha-256
postgresql_hba_config:
  - type: local
    database: all
    user: postgres
    auth_method: peer
  - type: local
    database: all
    user: all
    auth_method: reject
  - type: hostssl
    database: all
    user: all
    address: "127.0.0.1/32"
    auth_method: "{{ postgresql_auth_method }}"
  - type: hostssl
    database: all
    user: all
    address: "::1/128"
    auth_method: reject

# Databases
postgresql_databases: []
# - name: exampledb # required; the rest are optional
#   lc_collate: # defaults to 'en_US.UTF-8'
#   lc_ctype: # defaults to 'en_US.UTF-8'
#   encoding: # defaults to 'UTF-8'
#   template: # defaults to 'template0'
#   login_host: # defaults to 'localhost'
#   login_password: # defaults to not set
#   login_user: # defaults to '{{ postgresql_user }}'
#   login_unix_socket: # defaults to 1st of postgresql_unix_socket_dir
#   port: # defaults to not set
#   owner: # defaults to postgresql_user
#   state: # defaults to 'present'

# Database Users
postgresql_users_no_log: yes
postgresql_users: []
# - name: jdoe #required; the rest are optional
#   password: # defaults to not set
#   encrypted: # defaults to not set
#   priv: # defaults to not set
#   role_attr_flags: # defaults to not set
#   db: # defaults to not set
#   login_host: # defaults to 'localhost'
#   login_password: # defaults to not set
#   login_user: # defaults to '{{ postgresql_user }}'
#   login_unix_socket: # defaults to 1st of postgresql_unix_socket_dir
#   port: # defaults to not set
#   state: # defaults to 'present'