---
- name: Install `nzbget-git` using yay
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    name: nzbget-git
    state: latest
    use: yay

- name: Copy config file
  become: yes
  ansible.builtin.copy:
    dest: /var/lib/nzbget/.nzbget
    force: no
    group: nzbget
    mode: '0750'
    owner: nzbget
    remote_src: yes
    src: /usr/share/nzbget/nzbget.conf

- name: Enable nzbget service using systemd
  become: yes
  systemd:
    enabled: yes
    name: nzbget
    state: started