---
- name: Install dependencies via pacman
  become: yes
  pacman:
    name: "{{nzbget.dependencies}}"
    state: latest

- name: Install `nzbget-git` via yay
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    name: nzbget-git
    state: latest
    use: yay

- name: Copy config file
  become: yes
  ansible.builtin.copy:
    dest: "{{nzbget.path.config}}"
    force: no
    group: nzbget
    mode: '0750'
    owner: nzbget
    remote_src: yes
    src: /usr/share/nzbget/nzbget.conf

- name: Configure options via config file
  become: yes
  become_user: nzbget
  ansible.builtin.lineinfile:
    path: "{{nzbget.path.config}}"
    regexp: "{{item.regex}}"
    line: "{{item.line}}"
  with_items: "{{nzbget.config}}"

- name: Enable nzbget service via systemd
  become: yes
  systemd:
    enabled: yes
    name: nzbget
    state: started