---
- name: Install dependencies via pacman
  become: yes
  pacman:
    name:
      - p7zip
      - par2cmdline
      - unrar
      - unzip
    state: latest

- name: Install `nzbget-git` using yay
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    name: nzbget-git
    state: latest
    use: yay

- name: Copy config file
  become: yes
  ansible.builtin.copy:
    dest: "{{nzbget.path.config}}"
    force: no
    group: nzbget
    mode: '0750'
    owner: nzbget
    remote_src: yes
    src: /usr/share/nzbget/nzbget.conf

- name: Enable SSL options in config file
  become: yes
  become_user: nzbget
  ansible.builtin.lineinfile:
    path: "{{nzbget.path.config}}"
    regexp: "{{item.regex}}"
    line: "{{item.line}}"
  with_items:
    - line: SecureControl=yes
      regex: '^SecureControl='
    - line: "SecureCert={{ssl.path.cert}}"
      regex: '^SecureCert='
    - line: "SecureKey={{ssl.path.private}}"
      regex: '^SecureKey='

- name: Enable nzbget service using systemd
  become: yes
  systemd:
    enabled: yes
    name: nzbget
    state: started