---
- name: Update packages to latest
  become: yes
  community.general.pacman:
    update_cache: yes
    upgrade: yes

- name: Create the `aur_builder` user
  become: yes
  ansible.builtin.user:
    create_home: yes
    group: wheel
    name: aur_builder

- name: Allow the `aur_builder` user to run `sudo pacman` without a password
  become: yes
  ansible.builtin.lineinfile:
    create: yes
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    path: /etc/sudoers.d/11-install-aur_builder
    validate: 'visudo -cf %s'

- name: Install Yay
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    name: yay
    state: present
    use: makepkg