# Packages
pacman_binary: pacman
pacman_packages:
  - pacman-contrib
  - reflector
pacman_helper_package: yay

# User
pacman_helper_user: aur_builder
pacman_helper_user_shell: '/bin/bash'
pacman_helper_group: wheel

# Directories
pacman_binary_dir: /usr/bin
pacman_hooks_dir: /etc/pacman.d/hooks
pacman_sudoersd_dir: /etc/sudoers.d

# Paths
pacman_config_path: /etc/pacman.conf

# Permissions
pacman_hooks_dir_mode: 0644
pacman_sudoersd_file_mode: 0440

# Commands
pacman_sudo_validate: 'visudo -cf %s'
pacman_helper_builder: makepkg