# Packages
pacman_binary: pacman
pacman_helper_package: yay
pacman_contrib_package: pacman-contrib

# User
pacman_helper_user: aur_builder
pacman_helper_group: wheel

# Directories
pacman_binary_dir: /usr/bin
pacman_hooks_dir: /etc/pacman.d/hooks
pacman_sudoersd_dir: /etc/sudoers.d

# Paths
pacman_config_path: /etc/pacman.conf

# Commands
pacman_sudo_validate: 'visudo -cf %s'