---
- name: Download adguard
  unarchive:
    src: "https://github.com/AdguardTeam/AdGuardHome/releases/download/{{ adguard.version }}/AdGuardHome_linux_amd64.tar.gz"
    dest: "/home/{{ user.name }}"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    remote_src: yes

- name: Copy adguard configuration
  template:
    src: AdGuardHome.yaml.j2
    dest: "/home/{{ user.name }}/AdGuardHome/AdGuardHome.yaml"
    force: no
    owner: root
    group: root
    mode: 0644
  notify: Restart adguard

- name: Copy service file for adguard
  template:
    src: AdGuardHome.service.j2
    dest: /etc/systemd/system/AdGuardHome.service
    owner: root
    group: root
    mode: 0604
  notify: Restart adguard

- name: Start adguard service
  service:
    name: AdGuardHome
    state: started
    enabled: yes