---
- name: Install docker prerequisites via apt
  apt:
    install_recommends: no
    name: "{{ docker.prereqs }}"
    state: latest

- name: Add docker gpg key to apt
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"

- name: Add docker repo to apt
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    update_cache: true

- name: Install docker via apt
  apt:
    install_recommends: no
    name: "{{ docker.packages }}"
    state: latest

- name: Enable docker service
  service:
    name: docker
    state: started
    enabled: yes