---
- name: "Create group for {{ user.name }}"
  group:
    name: "{{ user.name }}"
    state: present
    gid: 1090

- name: "Add user {{ user.name }}"
  user:
    name: "{{ user.name }}"
    password: "{{ admin_password | password_hash('sha512', admin_password_salt) }}"
    groups: "{{ user.name }},docker"
    state: present
    shell: /bin/bash
    uid: 1090