---
- hosts: all
  
  tasks:
    - name: Upgrade all packages to the latest version
      apt:
        name: "*"
        state: latest
        update_cache: yes
        cache_valid_time: 3600
        autoclean: yes
        autoremove: yes
        
    - name: "Set timezone to {{ timezone }}"
      timezone:
        name: "{{ timezone }}"
        
    - name: Disable SSH password authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication.*yes'
        line: 'PasswordAuthentication no'
      register: password_auth
      
    - name: Restart SSHD if SSH password authentication has been disabled
      service:
        name: sshd
        state: restarted
      when: password_auth.changed
