---
- hosts: all

  vars_files:
    - defaults/main.yml

  handlers:
    - import_tasks: handlers/main.yml

  tasks:
    - name: Set localization settings for {{ localization_timezone }}
      include_tasks: tasks/localization.yml

    - name: Set network related settings for {{ network_hostname }}
      include_tasks: tasks/network.yml

    - name: Set sysctl related settings
      include_tasks: tasks/sysctl.yml

    - name: Setup & upgrade preferred packages
      include_tasks: tasks/packages.yml

    - name: Enable Unattended Upgrades
      include_tasks: tasks/unattended_upgrades.yml

    - name: Set user settings for {{ admin_user }} and {{ ansible_admin_user }}
      include_tasks: tasks/users.yml

    - name: Enable fail2ban protection
      include_tasks: tasks/fail2ban.yml

    - name: Enable rkhunter protection
      include_tasks: tasks/rkhunter.yml

    - name: Set SSHD settings
      include_tasks: tasks/sshd.yml

    - name: Set Postfix settings
      include_tasks: tasks/postfix.yml