---
- hosts: all

  vars_files:
    - defaults/main.yml

  tasks:
    - name: Set localization settings for {{ timezone }}
      include_tasks: tasks/set_localization.yml

    - name: Upgrade installed packages via Aptitude
      include_tasks: tasks/upgrade_packages.yml

    - name: Enable Unattended Upgrades
      include_tasks: tasks/unattended_upgrades.yml

    - name: Setup users
      include_tasks: tasks/setup_users.yml

    - name: Enable fail2ban protection
      include_tasks: tasks/fail2ban.yml