---
- hosts: all

  vars_files:
    - defaults/main.yml

  handlers:
    - import_tasks: handlers/main.yml

  tasks:
    - name: Set localization settings for {{ localization_timezone }}
      include_tasks: tasks/localization.yml

    - name: Set network related settings for {{ network_hostname }}
      include_tasks: tasks/network.yml

    - name: Setup & upgrade preferred packages
      include_tasks: tasks/packages.yml

    - name: Set AppArmor related settings
      include_tasks: tasks/apparmor.yml

    - name: Set up aide to track file system changes
      include_tasks: tasks/aide.yml

    - name: Set sysctl related settings
      include_tasks: tasks/sysctl.yml

    - name: Remove filesystems & network protocols via modprobe
      include_tasks: tasks/modprobe.yml

    - name: Set up firewall related settings
      include_tasks: tasks/firewall.yml

    - name: Disable system core dumps
      include_tasks: tasks/coredump.yml

    - name: Enable Unattended Upgrades
      include_tasks: tasks/unattended_upgrades.yml

    - name: Set user settings for {{ admin_user }} and {{ ansible_admin_user }}
      include_tasks: tasks/users.yml

    - name: Enable fail2ban protection
      include_tasks: tasks/fail2ban.yml

    - name: Enable rkhunter protection
      include_tasks: tasks/rkhunter.yml

    - name: Set SSHD settings
      include_tasks: tasks/sshd.yml

    - name: Set Postfix settings
      include_tasks: tasks/postfix.yml

    - name: Set system permissions
      include_tasks: tasks/permissions.yml