---
- name: Set /etc/shadow permissions
  become: yes
  file:
    path: /etc/shadow
    owner: root
    group: root
    mode: 0600

- name: List home directories
  find:
    file_type: directory
    paths: /home
  register: home_directories

- name: Set permissions
  file:
    mode: 0750
    path: "{{ item.path }}"
  with_items: "{{ home_directories.files }}"