---
- name: Check if daily aide cron exists
  stat:
    path: /etc/cron.daily/aide
  register: aidecron

- name: Copy aide service settings to /lib/systemd/system/
  template:
    src: lib/systemd/system/aidecheck.service.j2
    dest: /lib/systemd/system/aidecheck.service
    mode: 0644
    owner: root
    group: root
  when: not aidecron.stat.exists

- name: Setup aide check timer (instead of cron)
  template:
    src: lib/systemd/system/aidecheck.timer.j2
    dest: /lib/systemd/system/aidecheck.timer
    mode: 0644
    owner: root
    group: root
  when: not aidecron.stat.exists
  notify:
    - Restart systemd
    - Enable aidecheck

- name: stat Debian aide.db
  stat:
    path: /var/lib/aide/aide.db
  register: aidedb

- name: Initialize the aide database if it doesn't exist
  command: aideinit
  when: not aidedb.stat.exists