---
- name: Set /etc/security/limits.conf to disable coredump
  lineinfile:
    dest: /etc/security/limits.conf
    line: "*                hard    core            0"
    regexp: '(^#)?\*\s+hard\s+core\s+[0-9]+'
    state: present
    create: true
    insertbefore: "# End of file"

- name: Copy coredump.conf to /etc/systemd/ to restrict coredumps
  template:
    src: etc/systemd/coredump.conf.j2
    dest: /etc/systemd/coredump.conf
    owner: root
    group: root
    mode: 0644