---
- name: Copy fail2ban configurations to /etc/fail2ban/
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0600
  with_items:
    - { src: 'etc/fail2ban/jail.local.j2', dest: '/etc/fail2ban/jail.local' }
    - { src: 'etc/fail2ban/fail2ban.local.j2', dest: '/etc/fail2ban/fail2ban.local' }
    - { src: 'etc/fail2ban/jail.d/sshd.conf.j2', dest: '/etc/fail2ban/jail.d/sshd.conf' }
  notify: Restart fail2ban