---
- name: Set system hostname
  hostname:
    name: "{{ network.hostname }}"

- name: Copy hosts file to set basic dns settings
  template:
    src: etc/hosts.j2
    dest: /etc/hosts
    mode: 0644
    owner: root
    group: root

- name: Copy resolv.conf to set nameserver settings
  template:
    src: etc/resolv.conf.j2
    dest: /etc/resolv.conf
    mode: 0644
    owner: root
    group: root
  notify: Restart systemd

- name: Copy resolved.conf to /etc/systemd/resolved.conf
  template:
    src: etc/systemd/resolved.conf.j2
    dest: /etc/systemd/resolved.conf
    mode: 0644
    owner: root
    group: root
  notify: Restart systemd