---
- name: Set system hostname
  hostname:
    name: "{{ network_hostname }}"

- name: Copy hosts file to set basic dns settings
  template:
    src: etc/hosts.j2
    dest: /etc/hosts
    mode: 0644
    owner: root
    group: root

- name: Copy resolv.conf to set nameserver settings
  template:
    src: etc/resolv.conf.j2
    dest: /etc/resolv.conf
    mode: 0644
    owner: root
    group: root
  notify: Restart systemd

- name: Remove unneeded network protocols
  lineinfile:
    dest: /etc/modprobe.d/secure.conf
    regexp: "^(#)?install {{ item }}(\\s|$)"
    line: "install {{ item }} /bin/true"
    owner: root
    group: root
    mode: 0644
    create: true
  with_items: "{{ network.disable }}"

- name: Remove unneeded network protocols (modprobe)
  community.general.modprobe:
    name: "{{ item }}"
    state: absent
  with_items: "{{ network.disable }}"