---
- name: Install aptitude
  apt:
    name: aptitude
    state: latest
    install_recommends: no

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
    update_cache: yes
    cache_valid_time: 3600
    autoclean: yes
    autoremove: yes
    upgrade: 'full'
    install_recommends: no

- name: Install preferred system packages via APT
  apt:
    name: "{{ packages_preferred }}"
    state: latest
    install_recommends: no

- name: Remove unneccessary default packages
  apt:
    name: "{{ packages_blocklist }}"
    state: absent
    purge: 'yes'
  ignore_errors: true