---
- name: Install Sudo for escalated privileges management
  apt:
    name: sudo
    state: latest

- name: Add users {{ admin_user }} and {{ ansible_admin_user }}
  user:
    name: "{{ item.name }}"
    group: sudo
    password: "{{ admin_password | password_hash('sha512', admin_password_salt) }}"
    state: present
    shell: /bin/bash
    uid: "{{ item.uid }}"
  with_items:
    - { name: "{{ admin_user}}", uid: 1030 }
    - { name: "{{ ansible_admin_user }}", uid: 1080 }

- name: Grant {{ admin_user }} and {{ ansible_admin_user }} sudo privileges
  lineinfile:
    dest: /etc/sudoers.d/{{ item }}
    regexp: '^{{ item }}'
    line: '{{ item }} ALL=(ALL) ALL'
    state: present
    mode: 0440
    create: "yes"
    validate: 'visudo -cf %s'
  with_items:
    - "{{ admin_user }}"
    - "{{ ansible_admin_user }}"

- name: Set includedir to include /etc/sudoers.d
  lineinfile:
    dest: /etc/sudoers
    line: 'includedir /etc/sudoers.d'
    state: present
    validate: '/usr/sbin/visudo -cf %s'

- name: Set authorized key for {{ admin_user }} and {{ ansible_admin_user }}
  authorized_key:
    user: "{{ item.user }}"
    state: present
    exclusive: True
    key: "{{ item.key }}"
  with_items:
    - { user: "{{ admin_user }}", key: "{{ admin_public_key }}" }
    - { user: "{{ ansible_admin_user }}", key: "{{ admin_public_key }}" }