---
- name: Copy issue.net banner to warn off the baddies
  template:
    src: templates/etc/issue.j2
    dest: "/etc/{{ item }}"
    owner: root
    group: root
    mode: 0600
  with_items:
    - "issue"
    - "issue.net"

- name: Set permissions for sshd_config to 0600
  file:
    path: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0600
  notify: Restart sshd

- name: Copy SSH configuration template to be more secure
  template:
    src: templates/etc/ssh/sshd_config.j2
    dest: "/etc/ssh/sshd_config.d/{{sshd_config_name}}.conf"
    owner: root
    group: root
    mode: 0600
  notify: Restart sshd