---
- name: Copy sysctl configuration to /etc/sysctl.d/50-local.conf
  template:
    src: etc/sysctl.d/50-local.conf.j2
    dest: /etc/sysctl.d/50-local.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - Apply sysctl config
    - Restart sysctl

- name: Run handlers now to apply sysctl settings before continuing
  meta: flush_handlers

- name: Check if a reboot is needed
  register: reboot_required
  stat: path=/var/run/reboot-required get_md5=no

- name: Reboot the server if required
  reboot:
    msg: "Reboot initiated by Ansible due to kernel updates"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
  when: reboot_required.stat.exists