---
- name: Configure sysctl settings
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value|int }}"
    state: present
    sysctl_set: yes
    reload: yes
  with_dict: "{{ sysctl.conf | dictsort }}"

- name: Check if a reboot is needed
  register: reboot_required
  stat: path=/var/run/reboot-required get_md5=no

- name: Reboot the server if required
  reboot:
    msg: "Reboot initiated by Ansible due to kernel updates"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
  when: reboot_required.stat.exists