---
- name: Copy sysctl configuration to /etc/sysctl.d/secure.conf
  template:
    src: etc/sysctl.d/secure.conf.j2
    dest: /etc/sysctl.d/secure.conf
    owner: root
    group: root
    mode: 0644
  notify: Apply sysctl config