---
- name: Install Unattended Upgrades
  apt:
    name: unattended-upgrades
    state: present

- name: Copy unattended-upgrades configuration templates
  template:
    src: "{{ item }}.j2"
    dest: "/etc/apt/apt.conf.d/{{ item }}"
    owner: root
    group: root
    mode: '644'
  with_items:
    - 20auto-upgrades
    - 50unattended-upgrades