---
- name: Install Aptitude for package management
  apt:
    name: aptitude
    force_apt_get: yes

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
    update_cache: yes
    cache_valid_time: 3600
    autoclean: yes
    autoremove: yes