---
- name: Copy login.defs config
  template:
    src: templates/etc/login.defs.j2
    dest: /etc/login.defs
    owner: root
    group: root
    mode: 0600

- name: Harden password requirements for cracklib
  pamd:
    name: common-password
    type: password
    control: requisite
    module_path: pam_cracklib.so
    module_arguments: "{% for k, v in users.cracklib | dictsort -%}{{ k }}={{ v }} {% endfor %}"

- name: Set sudo commands to use pty and be logged
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "{{ item.regex }}"
    line: "{{ item.line }}"
    validate: "visudo -cf %s"
  with_items:
    - { line: "Defaults use_pty", regex: "^Defaults use_pty" }
    - { line: 'Defaults logfile="/var/log/sudo.log"', regex: "^Defaults logfile.*" }

- name: Remove unneccesary users
  user:
    name: "{{ item }}"
    state: absent
    remove: 'yes'
  with_items: "{{ users.blacklist }}"
  ignore_errors: true

- name: Create groups for users
  group:
    name: "{{ item.name }}"
    state: present
    gid: "{{ item.gid }}"
  with_items: "{{ vault.users.sudo }}"

- name: Add users
  user:
    name: "{{ item.name }}"
    groups: "sudo,{{ item.name }}"
    password: "{{ item.password }}"
    state: present
    shell: "{{ item.shell }}"
    uid: "{{ item.uid }}"
    expires: "{{ item.expires }}"
  with_items: "{{ vault.users.sudo }}"

- name: Grant sudo privileges
  lineinfile:
    dest: /etc/sudoers.d/{{ item.name }}
    regexp: '^{{ item.name }}'
    line: '{{ item.name }} ALL=(ALL) ALL'
    state: present
    mode: 0440
    create: "yes"
    validate: 'visudo -cf %s'
  with_items: "{{ vault.users.sudo }}"

- name: Set includedir to include /etc/sudoers.d
  lineinfile:
    dest: /etc/sudoers
    line: '#includedir /etc/sudoers.d'
    state: present
    validate: '/usr/sbin/visudo -cf %s'

- name: Set authorized keys
  authorized_key:
    user: "{{ item.name }}"
    state: present
    exclusive: True
    key: "{{ item.key }}"
  with_items: "{{ vault.users.sudo }}"

- name: Lock root account
  user:
    name: root
    password_lock: 'yes'