---
- name: Copy login.defs configuration template to be more secure
  template:
    src: templates/etc/login.defs.j2
    dest: /etc/login.defs
    owner: root
    group: root
    mode: 0600

- name: Harden password requirements for the cracklib pam module
  pamd:
    name: common-password
    type: password
    control: requisite
    module_path: pam_cracklib.so
    module_arguments: "{% for k, v in users.cracklib.items() | dictsort -%}{{ k }}={{ v }} {% endfor %}"

- name: Remove unneccesary default users
  user:
    name: "{{ item }}"
    state: absent
    remove: 'yes'
  with_items: "{{ users.blacklist }}"
  ignore_errors: true

- name: Create groups for {{ admin_user }} and {{ ansible_admin_user }}
  group:
    name: "{{ item.name }}"
    state: present
    gid: "{{ item.gid }}"
  with_items:
    - { name: "{{ admin_user}}", gid: 1030 }
    - { name: "{{ ansible_admin_user }}", gid: 1080 }

- name: Add users {{ admin_user }} and {{ ansible_admin_user }}
  user:
    name: "{{ item.name }}"
    groups: "sudo,{{ item.name }}"
    password: "{{ admin_password | password_hash('sha512', admin_password_salt) }}"
    state: present
    shell: /bin/bash
    uid: "{{ item.uid }}"
    expires: -1
  with_items:
    - { name: "{{ admin_user}}", uid: 1030 }
    - { name: "{{ ansible_admin_user }}", uid: 1080 }

- name: Grant {{ admin_user }} and {{ ansible_admin_user }} sudo privileges
  lineinfile:
    dest: /etc/sudoers.d/{{ item }}
    regexp: '^{{ item }}'
    line: '{{ item }} ALL=(ALL) ALL'
    state: present
    mode: 0440
    create: "yes"
    validate: 'visudo -cf %s'
  with_items:
    - "{{ admin_user }}"
    - "{{ ansible_admin_user }}"

- name: Set includedir to include /etc/sudoers.d
  lineinfile:
    dest: /etc/sudoers
    line: '#includedir /etc/sudoers.d'
    state: present
    validate: '/usr/sbin/visudo -cf %s'

- name: Set authorized key for {{ admin_user }} and {{ ansible_admin_user }}
  authorized_key:
    user: "{{ item.user }}"
    state: present
    exclusive: True
    key: "{{ item.key }}"
  with_items:
    - { user: "{{ admin_user }}", key: "{{ admin_public_key }}" }
    - { user: "{{ ansible_admin_user }}", key: "{{ admin_public_key }}" }

- name: Lock root account
  user:
    name: root
    password_lock: 'yes'