# Packages
mattermost_binary: mattermost
mattermost_packages:
  - mattermost
  # - python-psycopg2 # Not sure anymore if this is actually needed

# User
mattermost_user: mattermost
mattermost_user_shell: '/bin/bash'
mattermost_group: mattermost

# Directories
mattermost_config_dir: /etc/webapps/mattermost
mattermost_data_dir: /var/lib/mattermost