---
- name: Install `libpwquality` via pacman
  become: yes
  pacman:
    name: libpwquality
    state: latest

- name: Copy libpwquality configuration
  become: yes
  template:
    src: templates/etc/security/pwquality.conf.d/50-pwquality.conf.j2
    dest: /etc/security/pwquality.conf.d/50-pwquality.conf
    owner: root
    group: root
    mode: 0644