---
- name: Copy authorized_keys
  become: true
  ansible.posix.authorized_key:
    exclusive: yes
    key: "{{ sunlab_authorized_key }}"
    state: present
    user: "{{ item }}"
  with_items:
    - "{{ sunlab_ansible_admin }}"

- name: Copy /etc/issue banner
  become: true
  template:
    src: templates/etc/issue.j2
    dest: /etc/issue
    owner: root
    group: root
    mode: 0600

- name: Copy SSH config
  become: true
  template:
    src: templates/etc/ssh/sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0600
  notify: Restart sshd

- name: Enable sshd service
  become: true
  service:
    name: sshd
    enabled: yes
    state: started