---
- name: Check if i386 architecture is already enabled
  command: dpkg --print-foreign-architectures
  register: check_arch_i386
  changed_when: false

- name: Enable i386 architecture
  command: dpkg --add-architecture i386
  when: "'i386' not in check_arch_i386.stdout"