namespace: "sunlab"
name: "ubuntu"
version: "0.0.1"
readme: "README.md"
description: "Initialize & maintain a standard Ubuntu system in a security-forward approach."
authors:
  - "Sunny Thaper (https://github.com/sunnythaper)"
license:
  - "MIT"
tags:
  - homelab
  - sunlab
  - sunnythaper
  - ubuntu
repository: "https://github.com/sunnythaper/ansible_homelab"
dependencies:
  - 'community.general': '*'