---
- name: Install LinuxGSM dependencies
  apt:
    name: "{{ lgsm_dependencies }}"
    state: latest
    update_cache: yes
    dpkg_options: 'add-architecture i386'

- name: "Add user {{ lgsm_server }}"
  user:
    name: "{{ lgsm_server }}"
    password: "{{ admin_password | password_hash('sha512', admin_password_salt) }}"
    state: present
    shell: /bin/bash
    uid: 1000