---
- name: Enable i386 architecture
  command: dpkg --add-architecture i386
  register: add_arch_i386
  failed_when: "'Permission denied' in add_arch_i386.stdout"

- name: Accept SteamCMD EULA
  debconf:
    name: steamcmd
    question: steam/question
    value: 'I AGREE'
    vtype: select
  when: "'steamcmd:i386' in lgsm_dependencies"

- name: Install LinuxGSM dependencies
  apt:
    name: "{{ lgsm_dependencies }}"
    state: latest
    update_cache: yes

- name: "Create group for {{ lgsm_server }}"
  group:
    name: "{{ lgsm_server }}"
    state: present
    gid: 1000

- name: "Add user {{ lgsm_server }}"
  user:
    name: "{{ lgsm_server }}"
    password: "{{ admin_password | password_hash('sha512', admin_password_salt) }}"
    group: "{{ lgsm_server }}"
    state: present
    shell: /bin/bash
    uid: 1000

- name: Download LinuxGSM install script
  get_url:
    url: https://linuxgsm.sh
    dest: "/home/{{ lgsm_server }}/linuxgsm.sh"
    mode: '0775'
    owner: "{{ lgsm_server }}"
    group: "{{ lgsm_server }}"

- name: "Get {{ lgsm_server }} via LinuxGSM shell script"
  become: true
  become_user: "{{ lgsm_server }}"
  command: "/home/{{ lgsm_server }}/linuxgsm.sh {{ lgsm_server }}"
  args:
    chdir: "/home/{{ lgsm_server }}/"
    creates: "/home/{{ lgsm_server }}/{{ lgsm_server }}"
  register: setup_server
  changed_when: "'Installed' in setup_server.stdout"
  failed_when: "'Installed' not in setup_server.stdout"

- name: "Install {{ lgsm_server }}"
  become: true
  become_user: "{{ lgsm_server }}"
  command: "/home/{{ lgsm_server }}/{{ lgsm_server }} auto-install"
  args:
    chdir: "/home/{{ lgsm_server }}/"
    creates: "/home/{{ lgsm_server }}/serverfiles/*"
  register: install_server
  changed_when: "'Install Complete' in install_server.stdout"
  failed_when: "'Install Complete' not in install_server.stdout"