---
- name: "Restart {{ lgsm_server }} server"
  become_user: "{{ lgsm_server }}"
  command: "/home/{{ lgsm_server }}/{{ lgsm_server }} restart"
  register: restart_server
  changed_when: "'[  OK  ] Starting' in restart_server.stdout"
  # failed_when: "'FAIL' in restart_server.stdout"