---
- name: "Set AutoParty to true"
  telnet:
    port: 8081
    password: bbgn
    password_prompt: "password:"
    prompts:
      - "session."
    command:
      - sgs autoparty true
  register: autoparty
  changed_when: "'AutoParty set to True' in autoparty.stdout"