---
- name: Set AutoParty to true
  telnet:
    host: 127.0.0.1
    port: 8081
    login_prompt: "Please enter password:"
    user: {{ telnet_password }}
    prompts:
      - "[>|#]"
    command:
      - sgs autoparty true