---
- hosts: all
  
  tasks:
    - name: "Update {{ lgsm_server }} server to latest"
      become: yes
      become_user: "{{ lgsm_server }}"
      command: "/home/{{ lgsm_server }}/{{ lgsm_server }} update"
      register: update_server
      changed_when: "'No update available' not in update_server.stdout"
      failed_when: "'FAIL' in update_server.stdout"