- name: Restart Systemd
  become: true
  systemd:
    daemon_reload: yes
    name: '{{ mattermost_binary }}'
    state: restarted

- name: Restart Mattermost
  become: true
  service:
    name: "{{ mattermost_binary }}"
    state: restarted