---
- name: Check if database directory exists
  become: true
  file:
    path: "{{ postgresql_data_dir }}"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
    state: directory
    mode: 0700

- name: Check if database is initialized
  become: true
  ansible.builtin.stat:
    path: "{{ postgresql_data_dir }}/PG_VERSION"
  register: postgres_data

- name: Initialize database
  become: true
  become_user: "{{ postgresql_user }}"
  command: "{{ postgresql_bin_dir }}/initdb -D {{ postgresql_data_dir }}"
  when: not postgres_data.stat.exists
  # See: https://github.com/ansible/ansible/issues/16048#issuecomment-229012509
  vars:
    ansible_ssh_pipelining: true

- name: Start & enable service
  become: true
  systemd:
    enabled: yes
    name: "{{ postgresql_daemon }}"
    state: started