- name: Check if database directory exists
  become: true
  file:
    path: "{{ postgresql_data_dir }}"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
    state: directory
    mode: '{{ postgresql_data_dir_mode }}'

- name: Check if database is initialized
  become: true
  ansible.builtin.stat:
    path: "{{ postgresql_data_dir }}/{{ postgresql_init_check_file }}"
  register: __postgresql_data

- name: Initialize database
  become: true
  become_user: "{{ postgresql_user }}"
  command: "{{ postgresql_bin_dir | quote }}/{{ postgresql_init_binary | quote }} -D {{ postgresql_data_dir | quote }}"
  when: not __postgresql_data.stat.exists
  # See: https://github.com/ansible/ansible/issues/16048#issuecomment-229012509
  vars:
    ansible_ssh_pipelining: true
    ansible_remote_tmp: '{{ postgresql_ansible_dir }}'

- name: Create symbolic link to ssl
  become: true
  ansible.builtin.file:
    src: '{{ postgresql_ssl_cert_dir }}/{{ item }}'
    dest: '{{ postgresql_data_dir }}/{{ item }}'
    owner: '{{ postgresql_user }}'
    group: '{{ postgresql_group }}'
    state: link
    mode: '{{ postgresql_ssl_file_mode }}'
  with_items:
    - '{{ postgresql_ssl_cert_file  }}'
    - '{{ postgresql_ssl_key_file }}'

- name: Start & enable service
  become: true
  service:
    enabled: yes
    name: "{{ postgresql_binary }}"
    state: started