- name: Check if database directory exists
  become: true
  file:
    path: "{{ postgresql_data_dir }}"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
    state: directory
    mode: '{{ postgresql_data_dir_mode }}'

- name: Check if database is initialized
  become: true
  ansible.builtin.stat:
    path: "{{ postgresql_data_dir }}/{{ postgresql_init_check_file }}"
  register: __postgresql_data

- name: Initialize database
  become: true
  become_user: "{{ postgresql_user }}"
  command: "{{ postgresql_bin_dir }}/{{ postgresql_init_binary }} -D {{ postgresql_data_dir }}"
  when: not __postgresql_data.stat.exists
  # See: https://github.com/ansible/ansible/issues/16048#issuecomment-229012509
  vars:
    ansible_ssh_pipelining: true
    ansible_remote_tmp: '{{ postgresql_config_dir }}'

- name: Start & enable service
  become: true
  service:
    enabled: yes
    name: "{{ postgresql_binary }}"
    state: started