- name: Create user group
  become: true
  ansible.builtin.group:
    gid: '{{ postgresql_group_gid }}'
    name: '{{ postgresql_group }}'
    state: present

- name: Create user
  become: true
  ansible.builtin.user:
    create_home: no
    group: '{{ postgresql_group }}'
    home: '{{ postgresql_data_dir }}'
    name: '{{ postgresql_user }}'
    password: '{{ sunlab_seed_password | password_hash("sha512", 65534 | random(seed=sunlab_seed_salt) | string) }}'
    shell: '{{ postgresql_user_shell }}'
    state: present
    uid: '{{ postgresql_user_uid }}'

- name: Install packages
  become: true
  pacman:
    name: "{{ item }}"
    state: latest
  with_items: "{{ postgresql_packages }}"