---
- name: Install dependencies
  include_tasks: install.yml

- name: Initialize database
  include_tasks: initialize.yml

- name: Configure database daemon
  include_tasks: configure.yml

- name: Create users & databases
  include_tasks: database.yml
  when: postgresql_databases is defined or postgresql_users is defined