---
- name: Initialize database
  include_tasks: initialize.yml

- name: Configure database
  include_tasks: configure.yml

- name: Create users
  include_tasks: user.yml

- name: Create databases
  include_tasks: database.yml

- name: Configure users
  include_tasks: user_configure.yml