---
- name: Initialize database
  include_tasks: initialize.yml
  when:
    - postgres_databases is not defined
    - postgres_users is not defined

- name: Configure database
  include_tasks: configure.yml
  when:
    - postgres_databases is not defined
    - postgres_users is not defined

# - name: Create users
#   include_tasks: user.yml
#   when: postgresql_users is defined

# - name: Create databases
#   include_tasks: database.yml
#   when: postgresql_databases is defined

# - name: Configure users
#   include_tasks: user_configure.yml
#   when: postgresql_users is defined