---
- name: Initialize database
  include_tasks: initialize.yml
  when:
    - postgres_databases is empty
    - postgres_users is empty

- name: Configure database
  include_tasks: configure.yml
  when:
    - postgres_databases is empty
    - postgres_users is empty

- name: Create users
  include_tasks: user.yml
  when: postgresql_users is not empty

- name: Create databases
  include_tasks: database.yml
  when: postgresql_databases is not empty

- name: Configure users
  include_tasks: user_configure.yml
  when: postgresql_users is not empty