- name: Variables
  include_tasks: variables.yml

- name: Install
  include_tasks: install.yml

- name: Initialize
  include_tasks: initialize.yml

- name: Configure
  include_tasks: configure.yml

- name: Create users & databases
  include_tasks: database.yml
  when: postgresql_databases is defined or postgresql_users is defined