---
- name: Install dependencies
  include_tasks: install.yml

- name: Initialize database
  include_tasks: initialize.yml

- name: Configure database daemon
  include_tasks: configure.yml

- name: Create users
  include_tasks: user.yml
  when: postgresql_users is defined

- name: Create databases
  include_tasks: database.yml
  when: postgresql_databases is defined

- name: Configure users
  include_tasks: user_configure.yml
  when: postgresql_users is defined