---
- name: Initialize database
  include_tasks: initialize.yml
  when:
    - postgres_databases | length = 0
    - postgres_users | length = 0

- name: Configure database
  include_tasks: configure.yml
  when:
    - postgres_databases | length = 0
    - postgres_users | length = 0

- name: Create users
  include_tasks: user.yml
  when: postgresql_users | length > 0

- name: Create databases
  include_tasks: database.yml
  when: postgresql_databases | length > 0

- name: Configure users
  include_tasks: user_configure.yml
  when: postgresql_users | length > 0