- name: Include Archlinux OS variables
  ansible.builtin.include_vars: os/Archlinux.yml
  when: ansible_os_family == 'Archlinux'

- name: Include common config variables
  ansible.builtin.include_vars:
    file: config/common.yml
    hash_behaviour: merge

- name: Include log config variables
  ansible.builtin.include_vars:
    file: 'config/log_{{ postgresql_config_log }}.yml'
    hash_behaviour: merge

- name: Include ssl config variables
  ansible.builtin.include_vars:
    file: 'config/ssl_{{ postgresql_config_ssl }}.yml'
    hash_behaviour: merge