---
- name: Update system packages
  hosts: all
  roles:
    - pacman

- name: Configure basic host & network settings
  hosts: all
  roles:
    - resolvconf
    - hosts

- name: Harden system configuration to be security-forward
  hosts: all
  roles:
    - sshd
    - profile
    - logindefs
    - coredump
    - modprobe
    - sysctl
    - privileges

- name: Configure additional packages for additional security
  hosts: all
  roles:
    - iptables
    - certbot
    - libpwquality
    - logrotate
    - apparmor
    - rkhunter
    - lynis

# - name: Configure Teleport
#   hosts: all
#   roles:
#     - teleport

- name: Configure Graylog
  hosts: data:&graylog
  roles:
    - graylog

- name: Configure PostgreSQL
  hosts: data:&postgres
  roles:
    - postgresql

- name: Configure Mattermost
  hosts: chat:&mattermost
  roles:
    - mattermost

- name: Configure Cloudflared
  hosts: proxy:&cloudflared
  roles:
    - cloudflared

- name: Configure media center storage & delivery
  hosts: media:&mediacenter
  roles:
    - nfs
    - nzbget
    - prowlarr
    - sonarr
    - radarr
    - readarr
    - lidarr
    - plex