---
- name: Update system packages & install Teleport
  hosts: archlinux
  roles:
    - pacman
#     - teleport

- name: Configure basic host & network settings
  hosts: archlinux
  roles:
    - resolvconf
    - hosts

- name: Harden system configuration to be security-forward
  hosts: archlinux
  roles:
    - sshd
    - profile
    - logindefs
    - coredump
    - modprobe
    - sysctl
    - privileges

- name: Configure additional packages for additional security
  hosts: archlinux
  roles:
    - ssl
    - libpwquality
    - logrotate
    - apparmor
    # - rkhunter
    - lynis

- name: Configure PostgreSQL
  hosts: archlinux:&data
  roles:
    - postgresql

- name: Configure Mattermost
  hosts: archlinux:&chat
  roles:
    - mattermost

- name: Configure media center storage & delivery
  hosts: archlinux:&mediacenter
  roles:
    - nfs
    - nzbget
    - prowlarr
    - sonarr
    - radarr
    - readarr
    - lidarr
    - plex