- name: Install packages
  become: true
  pacman:
    name: "{{ item }}"
    state: latest
  with_items: "{{ logrotate_packages }}"

- name: Copy logrotate configuration
  become: true
  template:
    src: etc/logrotate.d/general.j2
    dest: /etc/logrotate.d/general
    owner: root
    group: root
    mode: 0644