# SSL
mattermost_ssl_group: '{{ certbot_group | default("certbot") }}'
mattermost_ssl_dir: '{{ certbot_config_live_dir | default("/etc/letsencrypt/live/") }}/{{ certbot_domain | default(ansible_fqdn) }}'
mattermost_ssl_cert_file: '{{ certbot_cert_file | default("fullchain.pem") }}'
mattermost_ssl_key_file: '{{ certbot_key_file | default("privkey.pem") }}'
mattermost_ssl_cert: '{{ mattermost_config_dir }}/{{ mattermost_ssl_cert_file }}'
mattermost_ssl_key: '{{ mattermost_config_dir }}/{{ mattermost_ssl_key_file }}'
mattermost_ssl_file_mode: 0700

# Config
mattermost_config_ssl:
  - option: SiteURL
    value: 'https://{{ ansible_fqdn }}'
  - option: ListenAddress
    value: ':8065'
    before: TLSCertFile
  # - option: ConnectionSecurity
  #   value: TLS
  - option: TLSCertFile
    value: '{{ mattermost_ssl_cert }}'
  - option: TLSKeyFile
    value: '{{ mattermost_ssl_key }}'