mattermost_config_ssl:
  - option: ListenAddress
    value: ':443'
    before: TLSCertFile
  - option: ConnectionSecurity
    value: TLS
  - option: Forward80to443
    value: 'true'
  - option: TLSCertFile
    value: '{{ mattermost_ssl_cert }}'
  - option: TLSKeyFile
    value: '{{ mattermost_ssl_key }}'

mattermost_config_capability: CAP_NET_BIND_SERVICE=+eip