mattermost_config_ssl:
  - option: ListenAddress
    value: ':443'
    after: LicenseFileLocation
  - option: ConnectionSecurity
    value: TLS
  - option: Forward80to443
    value: 'true'
  - option: TLSCertFile
    value: '{{ mattermost_ssl_cert }}'
  - option: TLSKeyFile
    value: '{{ mattermost_ssl_key }}'
