---
- name: Install ufw via apt
  apt:
    name: "{{ ufw.apt.install }}"
    state: latest
    install_recommends: no

- name: Set firewall rules via ufw
  ufw:
    delete: "{{ item.delete | default(omit) }}"
    direction: "{{ item.direction | default(omit) }}"
    from_ip: "{{ item.from_ip | default(omit) }}"
    from_port: "{{ item.from_port | default(omit) }}"
    insert: "{{ item.insert | default(omit) }}"
    interface: "{{ item.interface | default(omit) }}"
    log: "{{ item.log | default(omit) }}"
    logging: "{{ item.logging | default(omit) }}"
    name: "{{ item.name | default(omit) }}"
    policy: "{{ item.policy | default(omit) }}"
    port: "{{ item.port | default(omit) }}"
    proto: "{{ item.proto | default(omit) }}"
    rule: "{{ item.rule | default('allow') }}"
    state: "{{ item.state | default(omit) }}"
    to_ip: "{{ item.to_ip | default(omit) }}"
    to_port: "{{ item.to_port | default(omit) }}"
  with_items:
    - "{{ ufw.rules }}"
    - "{{ app.ufw.rules | default([]) }}"

- name: Set firewall application rules via ufw
  ufw:
    name: "{{ item.name }}"
    rule: "{{ item.rule if item.rule is defined else 'allow' }}"
  when: ufw.applications is defined
  with_items:
    - "{{ ufw.applications }}"
    - "{{ app.ufw.applications | default([]) }}"

- name: Copy ufw configuration to /etc/default/ufw
  template:
    src: etc/default/ufw.j2
    dest: /etc/default/ufw
    owner: root
    group: root
    mode: 0644
  notify: Restart ufw

- name: Start ufw
  ufw:
    state: "enabled"
    logging: "on"