---
- name: Install `nfs-utils` via pacman
  become: yes
  pacman:
    name: nfs-utils
    state: latest

- name: Create nas directories
  become: yes
  ansible.builtin.file:
    force: yes
    group: nzbget
    owner: nzbget
    path: "{{item}}"
    state: directory
  with_items:
    - "{{nfs.path.books.dir}}"
    - "{{nfs.path.downloads.dir}}"
    - "{{nfs.path.movies.dir}}"
    - "{{nfs.path.music.dir}}"
    - "{{nfs.path.software.dir}}"
    - "{{nfs.path.tv.dir}}"

- name: Mount an NFS volume
  become: yes
  ansible.posix.mount:
    fstype: nfs
    opts: "{{nfs.opts}}"
    path: "{{item.dir}}"
    src: "{{item.nas}}"
    state: mounted
  with_items:
    - dir: "{{nfs.path.books.dir}}"
      nas: "{{nfs.path.books.nas}}"
    - dir: "{{nfs.path.downloads.dir}}"
      nas: "{{nfs.path.downloads.nas}}"
    - dir: "{{nfs.path.movies.dir}}"
      nas: "{{nfs.path.movies.nas}}"
    - dir: "{{nfs.path.music.dir}}"
      nas: "{{nfs.path.music.nas}}"
    - dir: "{{nfs.path.software.dir}}"
      nas: "{{nfs.path.software.nas}}"
    - dir: "{{nfs.path.tv.dir}}"
      nas: "{{nfs.path.tv.nas}}"