---
- name: Install `nfs-utils` via pacman
  become: yes
  pacman:
    name: nfs-utils
    state: latest

- name: Create /mnt/nas directory
  become: yes
  ansible.builtin.file:
    force: yes
    group: mediacenter
    mode: '0570'
    path: "{{nfs.path.nas}}"
    state: directory

- name: Mount an NFS volume
  become: yes
  ansible.posix.mount:
    fstype: nfs
    opts: rw,sync,hard,intr
    path: "{{nfs.path.nas}}"
    src: 192.168.1.21:/mnt/SunNAS/Media
    state: mounted

- name: Create default directories
  become: yes
  ansible.builtin.file:
    force: yes
    group: mediacenter
    mode: '0570'
    path: "{{item}}"
    state: directory
  with_items: "{{nfs.path.defaults}}"