---
- name: Install `nfs-utils` via pacman
  pacman:
    name: nfs-utils
    state: latest

- name: Mount an NFS volume
  become: yes
  ansible.posix.mount:
    fstype: nfs
    opts: rw,sync,hard,intr
    path: /mnt/nas
    src: 192.168.1.21:/mnt/SunNAS/Media
    state: mounted