---
- name: List home directories
  become: true
  find:
    file_type: directory
    paths: /home
  register: home_directories

- name: Set permissions
  become: true
  file:
    mode: 0700
    path: "{{ item.path }}"
  with_items: "{{ home_directories.files }}"

- name: Set /etc/shadow permissions
  become: true
  file:
    path: /etc/shadow
    owner: root
    group: root
    mode: 0600

- name: Set /boot/grub/grub.cfg permissions
  become: true
  file:
    path: /boot/grub/grub.cfg
    owner: root
    group: root
    mode: 0700