---
- name: Create resolved.conf.d directory
  become: true
  file:
    path: /etc/systemd/resolved.conf.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Copy resolved.conf
  become: true
  template:
    src: etc/systemd/resolved.conf.d/resolved.conf.j2
    dest: /etc/systemd/resolved.conf.d/resolved.conf
    mode: 0644
    owner: root
    group: root
  notify: Restart systemd

- name: Create symbolic link to stub-resolv.conf
  become: true
  ansible.builtin.file:
    src: /run/systemd/resolve/stub-resolv.conf
    dest: /etc/resolv.conf
    owner: root
    group: root
    state: link
    mode: 0700
    force: true
  notify: Restart systemd