---
- name: Create resolved.conf.d directory
  become: true
  file:
    path: /etc/systemd/resolved.conf.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Copy resolved.conf
  become: true
  template:
    src: etc/systemd/resolved.conf.d/resolved.conf.j2
    dest: /etc/systemd/resolved.conf.d/resolved.conf
    mode: 0644
    owner: root
    group: root
  notify: Restart systemd

- name: Copy resolv.conf
  become: true
  template:
    src: etc/resolv.conf.j2
    dest: /etc/resolv.conf
    mode: 0644
    owner: root
    group: root
  notify: Restart systemd