---
- name: Create & configure groups
  become: true
  ansible.builtin.group:
    gid: '{{ item.gid | default(omit) }}'
    local: '{{ item.local | default(false) }}'
    name: '{{ item.name }}'
    non_unique: '{{ item.non_unique | default(false) }}'
    state: '{{ item.state | default("present") }}'
    system: '{{ item.system | default(omit) }}'
  with_items: "{{ user_groups }}"
  when: user_groups is defined
  tags:
    - default
    - add-group