- name: Update packages
  become: true
  community.general.pacman:
    update_cache: yes
    upgrade: yes
  tags:
    - update

- name: Install packages
  become: true
  pacman:
    name: '{{ item }}'
    state: latest
  with_items: '{{ pacman_packages }}'

- name: Create user
  become: true
  ansible.builtin.user:
    create_home: yes
    group: '{{ pacman_helper_group }}'
    name: '{{ pacman_helper_user }}'
    password: '{{ sunlab_seed_password | password_hash("sha512", 65534 | random(seed=sunlab_seed_salt) | string) }}'
    shell: '{{ pacman_helper_user_shell }}'
    state: present
    uid: '{{ pacman_helper_user_uid }}'

- name: Configure user to run passwordless pacman command
  become: true
  ansible.builtin.lineinfile:
    create: yes
    line: '{{ pacman_helper_user }} ALL=(ALL) NOPASSWD: {{ pacman_binary_dir }}/{{ pacman_binary }}'
    path: '{{ pacman_sudoersd_dir }}/11-{{ pacman_helper_user }}'
    validate: '{{ pacman_sudo_validate }}'
    owner: root
    group: root
    mode: '{{ pacman_sudoersd_file_mode }}'

- name: Install package manager helper
  become: true
  become_user: '{{ pacman_helper_user }}'
  kewlfft.aur.aur:
    name: '{{ pacman_helper_package }}'
    state: present
    use: '{{ pacman_helper_builder }}'