---
- name: Update packages
  become: true
  community.general.pacman:
    update_cache: yes
    upgrade: yes
  tags:
    - update

- name: Install packages
  become: true
  pacman:
    name: "{{ item }}"
    state: latest
  with_items: "{{ pacman_packages }}"
  when: pacman_packages is defined