---
- name: Update & install packages
  include_tasks: install.yml

- name: Configure package manager
  include_tasks: configure.yml

- name: Update & install helper packages
  include_tasks: helper.yml