---
- name: Update & install packages
  include_tasks: install.yml
  tags:
    - update

- name: Configure package manager
  include_tasks: configure.yml
  when:
    - pacman_packages is not defined
    - pacman_helper_packages is not defined

- name: Update & install helper packages
  include_tasks: helper.yml
  when: pacman_helper_packages is defined