---
- name: Update & install packages
  include_tasks: install.yml
  tags:
    - update

- name: Configure package manager
  include_tasks: configure.yml
  when:
    - pacman_packages  | length == 0
    - pacman_helper_packages | length == 0

- name: Update & install helper packages
  include_tasks: helper.yml
  when: pacman_helper_packages | length > 0