- name: Include Archlinux OS variables
  ansible.builtin.include_vars: os/Archlinux.yml
  when: ansible_os_family == 'Archlinux'

- name: Include mirrorlist config variables
  ansible.builtin.include_vars:
    file: 'config/reflector.yml'