---
- name: Install minikube via apt
  apt:
    deb: "{{ minikube.package }}"

- name: Get minikube status
  become: yes
  become_user: "{{ user.name }}"
  command: "minikube status"
  register: kubestatus
  changed_when: false
  failed_when: false

- name: Start minikube
  become: yes
  become_user: "{{ user.name }}"
  command: "minikube start --addons={{ minikube.conf.addons }} --driver=docker"
  when: "'Running' not in kubestatus.stdout"

- name: Get running pods
  become: yes
  become_user: "{{ user.name }}"
  command: "minikube kubectl get pods"
  register: pods
  changed_when: false
  failed_when: false

- name: Deploy awx operator via minikube
  become: yes
  become_user: "{{ user.name }}"
  command: "minikube kubectl -- apply -f {{ awx.operator.package }}"
  when: "'awx-operator' not in pods.stdout"
  register: operator

- name: Copy awx deployment template
  template:
    src: templates/awx.yml.j2
    dest: "/home/{{ user.name }}/awx.yml"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0604
    force: yes
  register: deployment

- name: Wait for awx operator to init
  pause:
    minutes: 1
  when: operator.changed

- name: Deploy awx service via minikube
  become: yes
  become_user: "{{ user.name }}"
  command: "minikube kubectl -- apply -f /home/{{ user.name }}/awx.yml"
  when: deployment.changed or operator.changed