---
- name: Flush handlers
  meta: flush_handlers

- name: Get admin password for awx
  become: yes
  become_user: "{{ user.name }}"
  command: "minikube kubectl -- get secret awx-admin-password -o jsonpath='{.data.password}'"
  changed_when: false
  register: adminpass

- name: Display awx login info
  debug:
    msg:
      - "{{ domain }}"
      - "USER: admin"
      - "PASS: {{ adminpass.stdout | b64decode }}"
      - BE SURE TO CHANGE YOUR LOGIN DETAILS IMMEDIATELY!