---
- name: Install sudo via apt
  apt:
    install_recommends: no
    name: "{{ users.apt.install }}"
    state: latest

- name: Set /etc/sudoers config
  lineinfile:
    dest: /etc/sudoers
    line: "{{ item.line }}"
    regexp: "{{ item.regex }}"
    state: present
    validate: "visudo -cf %s"
  with_items: "{{ users.sudoers.conf }}"

- name: Add users
  no_log: true
  user:
    expires: "{{ item.expires | default('-1') }}"
    groups: "sudo,{{ item.name }}"
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    shell: "{{ item.shell | default('/bin/bash') }}"
    state: present
    uid: "{{ item.uid }}"
  with_items:
    - "{{ app.users.sudo | default([]) }}"
    - "{{ vault.users.sudo | default([]) }}"

- name: Grant sudo privileges
  lineinfile:
    create: "yes"
    dest: /etc/sudoers.d/{{ item.name }}
    line: '{{ item.name }} ALL=(ALL) ALL'
    mode: 0440
    regexp: '^{{ item.name }}'
    state: present
    validate: 'visudo -cf %s'
  no_log: true
  with_items:
    - "{{ app.users.sudo | default([]) }}"
    - "{{ vault.users.sudo | default([]) }}"

- name: Set includedir to include /etc/sudoers.d
  lineinfile:
    dest: /etc/sudoers
    line: '#includedir /etc/sudoers.d'
    state: present
    validate: '/usr/sbin/visudo -cf %s'

- name: Set sudoers.d permissions
  file:
    group: root
    mode: 0750
    owner: root
    path: /etc/sudoers.d
    state: directory

- name: Set authorized keys
  authorized_key:
    exclusive: True
    key: "{{ item.key }}"
    state: present
    user: "{{ item.name }}"
  no_log: true
  with_items:
    - "{{ app.users.sudo | default([]) }}"
    - "{{ vault.users.sudo | default([]) }}"

- name: Lock root account
  user:
    name: root
    password_lock: 'yes'