---
- name: Add users
  no_log: true
  user:
    expires: "{{ item.expires | default('-1') }}"
    group: "{{ item.name }}"
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    shell: "{{ item.shell | default('/bin/bash') }}"
    state: present
  with_items: "{{ app.users.add }}"