---
- name: Create groups
  group:
    gid: "{{ item.gid }}"
    name: "{{ item.name }}"
    state: present
  no_log: true
  with_items:
    - "{{ users.add | default([]) }}"
    - "{{ users.sudo | default([]) }}"
    - "{{ users.system | default([]) }}"

- name: Remove users
  include_tasks: remove_users.yml
  when: users.remove is defined

- name: Add sudo users
  include_tasks: add_sudo_users.yml
  when: users.sudo is defined

- name: Set home directory permissions
  include_tasks: set_permissions.yml