---
- name: List home directories
  find:
    file_type: directory
    paths: /home
  register: home_directories

- name: Set permissions
  file:
    mode: 0750
    path: "{{ item.path }}"
  no_log: true
  with_items: "{{ home_directories.files }}"