---
- name: Check if i386 architecture is already enabled
  command: dpkg --print-foreign-architectures
  register: check_arch_i386
  changed_when: false

- name: Enable i386 architecture
  command: dpkg --add-architecture i386
  register: add_arch_i386
  when: "'i386' not in check_arch_i386.stdout"
  failed_when: "'Permission denied' in add_arch_i386.stdout"

- name: Accept SteamCMD EULA
  debconf:
    name: steamcmd
    question: steam/question
    value: 'I AGREE'
    vtype: select