---
- name: Set up aide to track file system changes
  include_tasks: aide.yml

- name: Set sysctl related settings
  include_tasks: sysctl.yml

- name: Remove filesystems & network protocols via modprobe
  include_tasks: modprobe.yml

- name: Set up firewall related settings
  include_tasks: firewall.yml

- name: Disable system core dumps
  include_tasks: coredump.yml

- name: Enable Unattended Upgrades
  include_tasks: unattended_upgrades.yml

- name: Setup users
  include_tasks: users.yml

- name: Enable fail2ban protection
  include_tasks: fail2ban.yml

- name: Enable rkhunter protection
  include_tasks: rkhunter.yml

- name: Set SSHD settings
  include_tasks: sshd.yml

- name: Set Postfix settings
  include_tasks: postfix.yml

- name: Set system permissions
  include_tasks: permissions.yml