---
- name: Enable rkhunter protection
  include_tasks: rkhunter.yml

- name: Set SSHD settings
  include_tasks: sshd.yml

- name: Set Postfix settings
  include_tasks: postfix.yml

- name: Set system permissions
  include_tasks: permissions.yml