---
- name: Remove filesystems & network protocols
  lineinfile:
    dest: /etc/modprobe.d/50-local.conf
    regexp: "^(#)?install {{ item }}(\\s|$)"
    line: "install {{ item }} /bin/true"
    state: present
    owner: root
    group: root
    mode: 0644
    create: true
  with_items:
    - "{{ filesystem.disable }}"
    - "{{ network.disable }}"