---
- name: Set permissions for sshd_config to 0600
  file:
    path: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0600
  notify: Restart sshd

- name: Set shadow file owner to root and mode to 0600
  file:
    path: /etc/shadow
    owner: root
    group: root
    mode: 0600

- name: Set cron job files to root and mode to 0700
  file:
    path: "/etc/{{ item }}"
    owner: root
    group: root
    mode: 0700
  with_items:
    - cron.d
    - cron.daily
    - cron.hourly
    - cron.weekly
    - cron.monthly

- name: Set crontab to root and mode to 0600
  file:
    path: /etc/crontab
    owner: root
    group: root
    mode: 0600

- name: Grab all home directories
  find:
    paths: /home
    file_type: directory
  register: home_directories

- name: Set home directory permissions to 0750
  file:
    mode: 0750
    path: "{{ item.path }}"
  with_items: "{{ home_directories.files }}"
  no_log: true

- name: Set sudoers.d permissions to 0600
  file:
    state: directory
    path: /etc/sudoers.d
    owner: root
    group: root
    mode: 0750