---
- hosts: all

  vars_files:
    - defaults/main.yml

  tasks:
    - name: Install pip
      include_tasks: tasks/pip.yml

    - name: Install ansible
      include_tasks: tasks/ansible.yml

    - name: Install docker
      include_tasks: tasks/docker.yml

    - name: Setup user
      include_tasks: tasks/user.yml

    - name: Install minikube
      include_tasks: tasks/minikube.yml

