---
- name: Install `readarr` using yay
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    name: readarr-nightly
    state: latest
    use: yay

- name: Add readarr user to nzbget group
  become: true
  ansible.builtin.user:
    name: readarr
    groups: nzbget
    append: yes

- name: Enable readarr service using systemd
  become: true
  systemd:
    enabled: yes
    name: readarr
    state: started