---
- name: Update rkhunter
  command: rkhunter --propupd

- name: Restart postfix
  service:
    name: postfix
    state: restarted
    enabled: yes

- name: Restart sshd
  service:
    name: sshd
    state: restarted
    enabled: yes