---
- name: Update rkhunter
  command: rkhunter --propupd

- name: Restart fail2ban
  service:
    name: fail2ban
    state: restarted
    enabled: yes

- name: Restart postfix
  service:
    name: postfix
    state: restarted
    enabled: yes

- name: Restart sshd
  service:
    name: sshd
    state: restarted
    enabled: yes

- name: Restart ufw
  service:
    name: ufw
    state: reloaded