---
- name: Apply coredump config via sysctl
  become: yes
  sysctl:
    name: kernel.core_pattern
    value: /dev/null
    state: present
    sysctl_set: yes
    reload: yes

- name: Copy coredump conf for systemd
  become: yes
  template:
    src: templates/etc/systemd/coredump.conf.d/50-coredump.conf.j2
    dest: /etc/systemd/coredump.conf.d/50-coredump.conf
    owner: root
    group: root
    mode: 0644
  notify: Reload systemd
