---
- name: Install `rkhunter` via pacman
  become: yes
  pacman:
    name: rkhunter
    state: latest

- name: Update rkhunter file properties database
  become: yes
  command: rkhunter --propupd

- name: Update rkhunter database
  become: yes
  command: rkhunter --update
  register: rkhunter_update
  failed_when: rkhunter_update.rc != 2 and rkhunter_update.rc != 0
  changed_when: false