---
- name: Install `rkhunter` via pacman
  become: yes
  pacman:
    name: rkhunter
    state: latest

- name: Check if rkhunter database exists
  become: yes
  stat:
    path: /var/lib/rkhunter/db/rkhunter.dat
  register: rkhunter_db

- name: Update rkhunter file properties database
  become: yes
  command: rkhunter --propupd
  register: rkhunter_propupd
  changed_when: "'File created' in rkhunter_propupd.stdout"
  when: not rkhunter_db.stat.exists

- name: Update rkhunter database
  become: yes
  command: rkhunter --update
  register: rkhunter_update
  changed_when: "'Updated' in rkhunter_update.stdout"
  failed_when: "'Update failed' in rkhunter_update.stdout"

- name: Configure rkhunter whitelist
  become: yes
  lineinfile:
    line: "SCRIPTWHITELIST={{ item }}"
    dest: /etc/rkhunter.conf
    state: present
  with_items: "{{ rkhunter.conf.whitelist }}"

- name: Configure rkhunter hidden files
  become: yes
  lineinfile:
    line: "ALLOWHIDDENFILE={{ item }}"
    dest: /etc/rkhunter.conf
    state: present
  with_items: "{{ rkhunter.conf.ignorehidden }}"

- name: Perform rkhunter check
  become: yes
  command: rkhunter --cronjob --report-warnings-only
  register: rkhunter_report
  changed_when: false
  failed_when: false

- name: Send rkhunter report via Mattermost
  mattermost:
    url: "{{ config.mattermost.url }}"
    api_key: "{{ config.mattermost.api_key }}"
    attachments:
      - text: "Report for **{{ ansible_fqdn }}**"
        color: '#530f52'
        title: rkhunter Report
        fields:
          - title: IP Address
            value: "{{ ansible_default_ipv4.address }}"
            short: yes
          - title: Operating System
            value: "{{ ansible_os_family }}"
            short: yes
          - title: Report
            value: "{{ rkhunter_report.stdout }}"
            short: no
  when: config.mattermost is defined and rkhunter_report.stdout != ""