---
- name: Install `rkhunter` via pacman
  become: yes
  pacman:
    name: rkhunter
    state: latest

- name: Check if rkhunter database exists
  become: yes
  stat:
    path: /var/lib/rkhunter/db/rkhunter.dat
  register: rkhunter_db

- name: Update rkhunter file properties database
  become: yes
  command: rkhunter --propupd
  register: rkhunter_propupd
  changed_when: "'File created' in rkhunter_propupd.stdout"
  when: not rkhunter_db.stat.exists

- name: Update rkhunter database
  become: yes
  command: rkhunter --update
  register: rkhunter_update
  changed_when: "'Updated' in rkhunter_update.stdout"
  failed_when: "'Update failed' in rkhunter_update.stdout"

- name: Perform rkhunter check
  become: yes
  command: rkhunter --cronjob --report-warnings-only
  changed_when: false
  failed_when: false