---
- name: Install `rkhunter` via pacman
  become: yes
  pacman:
    name: rkhunter
    state: latest

- name: Perform rkhunter check
  become: yes
  command: rkhunter --cronjob --report-warnings-only

- name: Update rkhunter file properties database
  become: yes
  command: rkhunter --propupd
  register: rkhunter_propupd
  changed_when: "'File created' in rkhunter_propupd.stdout or 'File updated' in rkhunter_propupd.stdout"

- name: Update rkhunter database
  become: yes
  command: rkhunter --update
  register: rkhunter_update
  failed_when: "'Update failed' in rkhunter_update.stdout"
  changed_when: "'Updated' in rkhunter_update.stdout"