---
- name: Disable systemd-resolved
  service:
    name: systemd-resolved
    state: stopped
    enabled: no

- name: Install unbound
  apt:
    name: unbound
    update_cache: yes
    state: latest
    install_recommends: no

- name: Get latest roots.hints declarations
  get_url:
    url: https://www.internic.net/domain/named.root
    dest: /var/lib/unbound/root.hints
    force: yes
    owner: root
    group: root
    mode: 0604

- name: Copy configuration for unbound
  template:
    src: adguard.conf.j2
    dest: /etc/unbound/unbound.conf.d/adguard.conf
    owner: root
    group: root
    mode: 0644
  register: unboundsetup

- name: Restart unbound
  service:
    name: unbound
    state: restarted
    enabled: yes
  when: unboundsetup.changed