iptables_rules:
  - chain: FORWARD
    policy: DROP
  - chain: OUTPUT
    policy: ACCEPT # TODO: Setup ipset and change to DROP
  - chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
  - chain: INPUT
    in_interface: lo
    jump: ACCEPT
  - chain: INPUT
    ctstate: INVALID
    jump: DROP
  - chain: INPUT
    ctstate: NEW
    icmp_type: 8
    jump: ACCEPT
    protocol: icmp
  - chain: INPUT
    ctstate: NEW
    destination_port: '{{ iptables_ssh_port }}'
    jump: ACCEPT
    protocol: tcp
    syn: match
  - chain: INPUT
    policy: ACCEPT # TODO: Setup ipset and change to DROP
  - chain: INPUT
    jump: REJECT
    protocol: udp
    reject_with: icmp-port-unreachable
  - chain: INPUT
    jump: REJECT
    protocol: tcp
    reject_with: tcp-reset
  - chain: INPUT
    jump: REJECT
    reject_with: icmp-proto-unreachable