# Policies
iptables_input_policy: DROP
iptables_forward_policy: DROP
iptables_output_policy: ACCEPT # TODO: Change to DROP

# Chains
iptables_input_tcp_chain: INPUT_TCP
iptables_input_udp_chain: INPUT_UDP

# INPUT ports
iptables_input_tcp_ports:
  - '{{ iptables_ssh_port }}'
  - 5432
  - 8065
iptables_input_udp_ports:
  - '{{ iptables_ssh_port }}'

# TODO: Setup further security measures and logging options from:
# https://wiki.archlinux.org/title/Simple_stateful_firewall#Tricking_port_scanners
# https://wiki.archlinux.org/title/Iptables#Logging