---
- name: Install fail2ban via apt
  apt:
    name: "{{ fail2ban.apt.install }}"
    state: latest
    install_recommends: no

- name: Copy fail2ban config
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0600
  with_items:
    - { src: 'etc/fail2ban/jail.local.j2', dest: '/etc/fail2ban/jail.local' }
    - { src: 'etc/fail2ban/fail2ban.local.j2', dest: '/etc/fail2ban/fail2ban.local' }
    - { src: 'etc/fail2ban/jail.d/sshd.conf.j2', dest: '/etc/fail2ban/jail.d/sshd.conf' }
  notify: Restart fail2ban