---
- name: Install `teleport` using yay
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    name: teleport-bin
    state: latest
    use: yay

- name: Create teleport directory
  become: true
  file:
    path: /etc/teleport
    state: directory
    owner: root
    group: root
    mode: 0600

- name: Copy teleport config
  become: true
  template:
    src: "templates/teleport.yaml.j2"
    dest: "/etc/teleport/teleport.yaml"
    owner: root
    group: root
    mode: 0600
  register: teleport_config

- name: Stop teleport if config changed
  become: true
  systemd:
    name: teleport
    state: stopped
  when: teleport_config.changed

- name: Start teleport service
  become: true
  systemd:
    name: teleport
    enabled: yes
    state: started