---
- name: Copy libpwquality configuration
  become: true
  template:
    src: templates/etc/security/pwquality.conf.d/50-pwquality.conf.j2
    dest: /etc/security/pwquality.conf.d/50-pwquality.conf
    owner: root
    group: root
    mode: 0644