---
- name: Install `nfs-utils` via pacman
  become: true
  pacman:
    name: nfs-utils
    state: latest

- name: Mount an NFS volume
  become: true
  ansible.posix.mount:
    fstype: nfs
    opts: "{{nfs.opts}}"
    path: "{{item.dir}}"
    src: "{{item.nas}}"
    state: mounted
  with_items:
    - "{{nfs.path.books}}"
    - "{{nfs.path.downloads}}"
    - "{{nfs.path.movies}}"
    - "{{nfs.path.music}}"
    - "{{nfs.path.software}}"
    - "{{nfs.path.tv}}"