- name: Copy /etc/host file
  become: true
  template:
    src: etc/host.j2
    dest: /etc/host
    owner: root
    group: root
    mode: 0644

- name: Check if /etc/hosts is managed by cloud-init
  stat:
    path: /etc/cloud/templates/hosts.arch.tmpl
  register: managed_hosts_file

- name: Copy /etc/hosts file
  become: true
  template:
    src: etc/hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
  when: not managed_hosts_file.stat.exists

- name: Copy /etc/cloud/templates/hosts.arch.tmpl file
  become: true
  template:
    src: etc/cloud/templates/hosts.arch.tmpl
    dest: etc/cloud/templates/hosts.arch.tmpl
    owner: root
    group: root
    mode: 0644
  when: managed_hosts_file.stat.exists