- name: Copy /etc/host file
  become: true
  template:
    src: etc/host.j2
    dest: /etc/host
    owner: root
    group: root
    mode: 0644

- name: Copy /etc/hosts file
  become: true
  template:
    src: etc/hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644