---
linuxgsm_dependencies:
  - curl
  - wget
  - file
  - tar
  - bzip2
  - gzip
  - unzip
  - bsdmainutils
  - python
  - util-linux
  - ca-certificates
  - binutils
  - bc
  - jq
  - tmux
  - netcat
  - lib32gcc1
  - lib32stdc++6
  - steamcmd:i386
  - zlib1g  # FOR STATIONEERS