
---
- hosts: all
  
  tasks:
    - name: Get latest Mattermost release JSON from Github
      uri:
        url: https://api.github.com/repos/mattermost/mattermost-server/releases/latest
        return_content: true
      register: json_reponse

    - name: Download & unarchive Mattermost tarball
      unarchive:
        src: "{{ json_reponse.json.tarball_url }}"
        dest: /tmp/
        creates: /tmp/mattermost-latest/
        remote_src: yes
        list_files: yes
        extra_opts:
          - --transform
          - s/^xxx/yyy/
      register: archive_contents
