
---
- hosts: all
  
  tasks:
    - name: Get latest Mattermost release JSON from Github
      uri:
        url: https://api.github.com/repos/mattermost/mattermost-server/releases/latest
        return_content: true
      register: json_reponse

    - name: Identify & download tarball file from JSON
      get_url:
        url: "{{ json_reponse.json.tarball_url }}"
        dest: /tmp/{{ json_reponse.json.name }}.tar.gz

    - name: Unarchive Mattermost tarball
      unarchive:
        src: /tmp/{{ json_reponse.json.name }}.tar.gz
        dest: /tmp/
        remote_src: yes
