
---
- hosts: all
  
  tasks:
    - name: Getting latest Mattermost release JSON from Github
      uri:
        url: https://api.github.com/repos/mattermost/mattermost-server/releases/latest
        return_content: true
      register: json_reponse

    - name: Downloading & unarchiving Mattermost tarball
      unarchive:
        src: "{{ json_reponse.json.tarball_url }}"
        dest: /tmp/
        remote_src: yes
        list_files: yes
      register: archive_contents
      
    - name: Creating a directory for database backups
      file:
        path: /opt/mattermost-backups/db
        mode: 0775
        owner: root
        state: directory
      
    - name: Backing up Postgres database
      shell: "pg_dumpall --clean -U mattermost > /opt/mattermost-backups/db/{{ ansible_date_time.iso8601 }}.db"
      
    - name: Creating a directory for application backups
      file:
        path: /opt/mattermost-backups/app
        mode: 0775
        owner: root
        state: directory
        
    - name: Backing up Mattermost application
      copy:
        src: /opt/mattermost
        dest: /opt/mattermost-backups/app/{{ ansible_date_time.iso8601 }}/
        remote_src: yes
        mode: preserve
        group: mattermost
        owner: mattermost
