
---
- hosts: all
  
  tasks:
    - name: Getting latest Mattermost release JSON from Github
      uri:
        url: https://api.github.com/repos/mattermost/mattermost-server/releases/latest
        return_content: true
      register: json_reponse

    - name: Downloading & unarchiving Mattermost tarball
      unarchive:
        src: "https://releases.mattermost.com/{{ json_reponse.json.name | replace('v','') }}/mattermost-{{ json_reponse.json.name | replace('v','') }}-linux-amd64.tar.gz"
        dest: /tmp/
        remote_src: yes
      
    - name: Stop service mattermost, if started
      service:
        name: mattermost
        state: stopped
      
    - name: Creating a directory for database backups
      file:
        path: /opt/mattermost-backups/db
        mode: 0775
        owner: root
        state: directory
      
    - name: Backing up Postgres database
      shell: "pg_dumpall --clean -U mattermost > /opt/mattermost-backups/db/{{ ansible_date_time.iso8601 }}.db"
      
    - name: Creating a directory for application backups
      file:
        path: /opt/mattermost-backups/app
        mode: 0775
        owner: root
        state: directory
        
    - name: Backing up Mattermost application
      copy:
        src: /opt/mattermost
        dest: /opt/mattermost-backups/app/{{ ansible_date_time.iso8601 }}
        remote_src: yes
        mode: preserve
        group: mattermost
        owner: mattermost
        
    - name: Remove current Mattermost files
      shell: "find /opt/mattermost/ /opt/mattermost/client/ -mindepth 1 -maxdepth 1 \\! \\( -type d \\( -path /opt/mattermost/client -o -path /opt/mattermost/client/plugins -o -path /opt/mattermost/config -o -path /opt/mattermost/logs -o -path /opt/mattermost/plugins -o -path /opt/mattermost/data \\) -prune \\) | sort | sudo xargs rm -r"
      ignore_errors: yes
      
    - name: Remove config.json file from update before transferring
      file:
        path: /tmp/mattermost/config/config.json
        state: absent
      
    - name: Copy contents of latest release to Mattermost folder
      copy:
        src: /tmp/mattermost
        dest: /opt/
        remote_src: yes
        directory_mode: yes
        mode: preserve
        group: mattermost
        owner: mattermost
      
    - name: Start service mattermost
      service:
        name: mattermost
        state: started
