---
users:
  add: []
  sudo: "{{ vault.users.sudo | default([omit]) }}"
  sudoers:
    conf:
      - line: 'Defaults logfile="/var/log/sudo.log"'
        regex: "^Defaults logfile.*"
      - line: Defaults use_pty
        regex: "^Defaults use_pty"
  system: []
  remove:
    - games
    - gnats
    - irc
    - list
    - news
    - sync
    - uucp