---
- name: Accept SteamCMD EULA
  debconf:
    name: steamcmd
    question: steam/question
    value: 'I AGREE'
    vtype: select
  when: "'steamcmd:i386' in apt.dependencies"

- name: Install dependencies
  apt:
    name: "{{ apt.dependencies }}"
    state: latest
    update_cache: yes