---
- name: Copy Space Engineers configuration to dedicated server folder
  template:
    src: SpaceEngineers-Dedicated.cfg.j2
    dest: "{{ directories.steam }}/SpaceEngineers-Dedicated.cfg"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0644

- name: Install Space Engineers via steamcmd
  become: true
  become_user: "{{ user.name }}"
  command: "/usr/games/steamcmd +login anonymous +@sSteamCmdForcePlatformType windows +force_install_dir {{ directories.steam }} +app_update 298740 +quit"
  register: steamcmd_install
  changed_when: "'already up to date.' not in steamcmd_install.stdout"

- name: "Extract world archive into {{ directories.world }}"
  unarchive:
    src: files/star_system.zip
    dest: "{{ directories.world }}"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    creates: Sandbox.sbc

- name: Copy service file for Space Engineers
  template:
    src: spaceengineers.service.j2
    dest: /etc/systemd/system/spaceengineers.service
    owner: root
    group: root
    mode: 0755