---
- name: Copy Space Engineers configuration to dedicated server folder
  template:
    src: SpaceEngineers-Dedicated.cfg.j2
    dest: "{{ directories.steam }}/SpaceEngineers-Dedicated.cfg"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0644

- name: Install steamcmd
  apt:
    name: steamcmd:i386
    state: latest
    install_recommends: yes

- name: Install Space Engineers via steamcmd
  become: true
  become_user: "{{ user.name }}"
  command: "/usr/games/steamcmd +login anonymous +@sSteamCmdForcePlatformType windows +force_install_dir {{ directories.steam }} +app_update 298740 +quit"
  register: steamcmd_install
  changed_when: "'already up to date.' not in steamcmd_install.stdout"

- name: "Extract world archive into {{ directories.world }}"
  unarchive:
    src: files/star_system.zip
    dest: "{{ directories.world }}"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    creates: Sandbox.sbc

# env WINEARCH={{ wine.arch }} WINEDEBUG={{ wine.debug }} WINEPREFIX={{ directories.wineprefix }} wine {{ directories.steam }}/DedicatedServer64/SpaceEngineersDedicated.exe -noconsole -path Z:{{ directories.steam | replace('/','\\\\') }} -ignorelastsession
# env WINEARCH=win64 WINEDEBUG=-all WINEPREFIX=/home/seserver/wineprefix wine /home/seserver/serverfiles/server/DedicatedServer64/SpaceEngineersDedicated.exe -noconsole -path Z:\\home\\seserver\\serverfiles\\server -ignorelastsession
