---
- name: Copy Space Engineers configuration to dedicated server folder
  template:
    src: SpaceEngineers-Dedicated.cfg.j2
    dest: "{{ directories.steam }}/SpaceEngineers-Dedicated.cfg"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0644

- name: Install steamcmd
  apt:
    name: steamcmd:i386
    state: latest
    install_recommends: yes

- name: Install Space Engineers via steamcmd
  become: true
  become_user: "{{ user.name }}"
  command: "steamcmd +login anonymous +@sSteamCmdForcePlatformType windows +force_install_dir {{ directories.steam }} +app_update 298740 +quit"


# env WINEARCH={{ wine.arch }} WINEDEBUG={{ wine.debug }} WINEPREFIX={{ directories.wineprefix }} wine {{ directories.steam }}/DedicatedServer64/SpaceEngineersDedicated.exe -noconsole -path Z:{{ directories.steam | replace('/','\\\\') }} -ignorelastsession