---
- name: Add wine repository key to apt
  apt_key:
    url: https://dl.winehq.org/wine-builds/winehq.key
    keyring: /etc/apt/trusted.gpg.d/winehq.gpg

- name: Add WineHQ repository
  apt_repository:
    repo: deb https://dl.winehq.org/wine-builds/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release }} main

- name: Install wine
  apt:
    name: "{{ wine.package }}"
    state: latest
    install_recommends: yes

- name: Check if winetricks is already installed
  stat:
    path: /usr/local/bin/winetricks
  register: winetricks

- name: Get currently installed winetricks version
  command: 'winetricks -V'
  register: winetricks_version
  changed_when: false
  when: winetricks.stat.exists

- name: Getting latest winetricks release JSON from Github
  uri:
    url: https://api.github.com/repos/mattermost/mattermost-server/releases/latest
    return_content: true
  register: release
  changed_when: release.json.name not in winetricks_version.stdout
  when: winetricks.stat.exists

- name: Download latest winetricks from Github
  get_url:
    url: https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks
    dest: /usr/local/bin/winetricks
    force: yes
    owner: root
    group: root
    mode: 0755
  when: release.changed or not winetricks.stat.exists

- name: Download latest winetricks bash completion script from Github
  get_url:
    url: https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks.bash-completion
    dest: /usr/share/bash-completion/completions/winetricks
    force: yes
    owner: root
    group: root
    mode: 0644
  when: release.changed or not winetricks.stat.exists

- name: Copy install-winetricks bash script to ~/scripts
  template:
    src: install-winetricks.j2
    dest: "{{ directories.scripts }}/install-winetricks.sh"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0755

- name: "Run install-winetricks for setup commands"
  become: true
  become_user: "{{ user.name }}"
  command: "{{ directories.scripts }}/install-winetricks.sh"
  register: install_winetricks
  when: release.changed