---
- name: Restart sshd
  service:
    name: sshd
    state: restarted

- name: Restart postfix
  service:
    name: postfix
    state: restarted

- name: Restart systemd
  systemd:
    daemon_reload: 'yes'