---
- name: Apply sysctl config
  command: sysctl --load /etc/sysctl.d/secure.conf

- name: Restart fail2ban
  service:
    name: fail2ban
    state: restarted
    enabled: yes

- name: Restart postfix
  service:
    name: postfix
    state: restarted
    enabled: yes

- name: Restart systemd
  systemd:
    daemon_reload: 'yes'

- name: Restart sshd
  service:
    name: sshd
    state: restarted
    enabled: yes

- name: Restart sysctl
  service:
    name: systemd-sysctl
    state: restarted