---
- hosts: all

  vars_files:
    - defaults/main.yml
    - "vars/{{ lgsm_server }}.yml"

  tasks:
    - name: "Restart {{ lgsm_server }}"
      include_tasks: tasks/restart_server.yml

    - name: Give LGSM 45 seconds to restart
      pause:
        seconds: 45
      when:
        - lgsm_server == 'sdtdserver'

    - name: "Set AutoParty to true"
      include_tasks: tasks/sdtdserver_set_autoparty_true.yml
      when:
        - lgsm_server == 'sdtdserver'
        - sdtdserver_AutoParty | bool