---
- name: Create groups
  group:
    gid: "{{ item.gid }}"
    name: "{{ item.name }}"
    state: present
  no_log: true
  with_items:
    - "{{ app.users.add | default([]) }}"
    - "{{ app.users.docker | default([]) }}"
    - "{{ app.users.sudo | default([]) }}"
    - "{{ app.users.system | default([]) }}"
    - "{{ vault.users.sudo | default([]) }}"

- name: Remove users
  include_tasks: remove_users.yml
  when: app.users.remove is defined or users.remove is defined

- name: Add users
  include_tasks: add_users.yml
  when: app.users.add is defined

- name: Add docker users
  include_tasks: add_docker_users.yml
  when: app.users.docker is defined

- name: Add sudo users
  include_tasks: add_sudo_users.yml
  when: app.users.sudo is defined or vault.users.sudo is defined

- name: Set home directory permissions
  include_tasks: set_permissions.yml