---
- name: Install LinuxGSM dependencies
  apt:
    name: "{{ linuxgsm_dependencies }}"
    state: latest
    update_cache: yes

- name: Download LinuxGSM install script
  get_url:
    url: https://linuxgsm.sh
    dest: "/home/{{ linuxgsm.server }}/linuxgsm.sh"
    mode: '0775'
    owner: "{{ linuxgsm.server }}"
    group: "{{ linuxgsm.server }}"

- name: "Get {{ linuxgsm.server }} via LinuxGSM shell script"
  become: true
  become_user: "{{ linuxgsm.server }}"
  command: "/home/{{ linuxgsm.server }}/linuxgsm.sh {{ linuxgsm.server }}"
  args:
    chdir: "/home/{{ linuxgsm.server }}/"
    creates: "/home/{{ linuxgsm.server }}/{{ linuxgsm.server }}"
  register: setup_server
  changed_when: "'Installed' in setup_server.stdout"

- name: "Download {{ linuxgsm.server }} from Steam"
  become: true
  become_user: "{{ linuxgsm.server }}"
  command: "/home/{{ linuxgsm.server }}/{{ linuxgsm.server }} auto-install"
  args:
    chdir: "/home/{{ linuxgsm.server }}/"
    creates: "/home/{{ linuxgsm.server }}/serverfiles/*"
  register: install_server
  changed_when: "'Install Complete' in install_server.stdout"

- name: "Update {{ linuxgsm.server }} server to latest"
  become: true
  become_user: "{{ linuxgsm.server }}"
  command: "/home/{{ linuxgsm.server }}/{{ linuxgsm.server }} update"
  register: update_server
  changed_when: "'No update available' not in update_server.stdout"
  failed_when: "'FAIL' in update_server.stdout"