- name: Configure main settings
  become: true
  ansible.builtin.lineinfile:
    backrefs: yes
    dest: '{{ mattermost_config_dir }}/{{ mattermost_config_file }}'
    regex: '^(\s+)"{{ item.option }}": ".*"(,)?'
    line: '\1"{{ item.option }}": "{{ item.value }}"\2'
    state: present
    owner: '{{ mattermost_user }}'
    group: '{{ mattermost_group }}'
    mode: '{{ mattermost_config_file_mode }}'
  no_log: '{{ mattermost_config_no_log }}'
  with_items:
    - '{{ mattermost_config_db}}'