- name: Generate password
  ansible.builtin.set_fact:
    mattermost_database_password: '{{ lookup("ansible.builtin.password", "/dev/null chars=ascii_lowercase,ascii_uppercase,digits length=40", seed=sunlab_seed_password) }}'

- name: Configure main settings
  become: true
  ansible.builtin.lineinfile:
    backrefs: yes
    dest: '{{ mattermost_config_dir }}/{{ mattermost_config_file }}'
    regex: '^(\s+)"{{ item.option }}": ".*"(,)?'
    insertbefore: '^\s+"{{ item.before | default(omit) }}.*""'
    firstmatch: yes
    line: '\1"{{ item.option }}": "{{ item.value }}"\2'
    state: present
    owner: '{{ mattermost_user }}'
    group: '{{ mattermost_group }}'
    mode: '{{ mattermost_config_file_mode }}'
  no_log: '{{ mattermost_config_no_log }}'
  with_items:
    - '{{ mattermost_config_db}}'
    - '{{ mattermost_config_ssl }}'
  notify: Restart Mattermost