- name: Configure main settings
  become: true
  ansible.builtin.lineinfile:
    backrefs: yes
    dest: '{{ mattermost_config_dir }}/{{ mattermost_config_file }}'
    regex: '^(\s+)"{{ item.option }}": ".*"(,)?'
    insertbefore: '^\s+"{{ item.before | default(omit) }}.*""'
    firstmatch: yes
    line: '\1"{{ item.option }}": "{{ item.value }}"\2'
    state: present
    owner: '{{ mattermost_user }}'
    group: '{{ mattermost_group }}'
    mode: '{{ mattermost_config_file_mode }}'
  no_log: '{{ mattermost_config_no_log }}'
  with_items:
    - '{{ mattermost_config_db}}'
    - '{{ mattermost_config_ssl }}'
  notify: Restart Mattermost

- name: Configure ssl capability
  become: true
  community.general.capabilities:
    path: '{{ mattermost_binary_path }}'
    capability: '{{ mattermost_config_capability }}'
    state: present
  when: mattermost_ssl == 'enabled'
  notify: Restart Mattermost

# - name: Configure service settings
#   become: true
#   ansible.builtin.lineinfile:
#     dest: '{{ mattermost_service_dir }}/{{ mattermost_service_file }}'
#     regex: '^{{ item.option }}=(.*)?'
#     insertbefore: '^{{ item.before | default(omit) }}.*$'
#     line: '{{ item.option }}={{ item.value }}'
#     create: yes
#     state: present
#     owner: root
#     group: root
#     mode: '{{ mattermost_service_file_mode }}'
#   with_items: '{{ mattermost_config_service }}'
#   notify: Restart Mattermost