- name: Create database user
  become: true
  become_user: "{{ mattermost_database_admin_user }}"
  community.postgresql.postgresql_user:
    name: "{{ mattermost_database_user }}"
    password: "{{ mattermost_database_password }}"
    state: present
  no_log: "{{ mattermost_config_no_log }}"
  # See: https://github.com/ansible/ansible/issues/16048#issuecomment-229012509
  vars:
    ansible_ssh_pipelining: true
  delegate_to: '{{ mattermost_database_host }}'
  delegate_facts: no

- name: Create database
  become: true
  become_user: "{{ mattermost_database_admin_user }}"
  community.postgresql.postgresql_db:
    name: "{{ mattermost_database }}"
    owner: "{{ mattermost_database_user }}"
    state: present
  # See: https://github.com/ansible/ansible/issues/16048#issuecomment-229012509
  vars:
    ansible_ssh_pipelining: true
  delegate_to: '{{ mattermost_database_host }}'
  delegate_facts: no

- name: Configure database user
  become: true
  become_user: "{{ mattermost_database_admin_user }}"
  community.postgresql.postgresql_user:
    name: "{{ mattermost_database_user }}"
    password: "{{ mattermost_database_password }}"
    db: "{{ mattermost_database }}"
    state: present
  no_log: "{{ mattermost_config_no_log }}"
  # See: https://github.com/ansible/ansible/issues/16048#issuecomment-229012509
  vars:
    ansible_ssh_pipelining: true
  delegate_to: '{{ mattermost_database_host }}'
  delegate_facts: no

- name: Create symbolic link to ssl
  become: true
  ansible.builtin.file:
    src: '{{ mattermost_ssl_dir }}/{{ item }}'
    dest: '{{ mattermost_config_dir }}/{{ item }}'
    owner: '{{ mattermost_user }}'
    group: '{{ mattermost_group }}'
    state: link
    mode: '{{ mattermost_ssl_file_mode }}'
  with_items:
    - '{{ mattermost_ssl_cert_file  }}'
    - '{{ mattermost_ssl_key_file }}'

- name: Create Bleve directory
  become: true
  ansible.builtin.file:
    mode: '{{ mattermost_bleve_dir_mode }}'
    path: '{{ mattermost_bleve_dir }}'
    owner: '{{ mattermost_user }}'
    group: '{{ mattermost_group }}'
    state: directory