- name: Create user group
  become: true
  ansible.builtin.group:
    gid: '{{ mattermost_group_gid }}'
    name: '{{ mattermost_group }}'
    state: present

- name: Create user
  become: true
  ansible.builtin.user:
    create_home: no
    groups:
      - '{{ mattermost_group }}'
      - '{{ mattermost_ssl_group }}'
    home: '{{ mattermost_data_dir }}'
    name: '{{ mattermost_user }}'
    shell: '{{ mattermost_user_shell }}'
    state: present
    uid: '{{ mattermost_user_uid }}'

- name: Install packages
  become: true
  pacman:
    name: "{{ item }}"
    state: latest
  with_items: "{{ mattermost_packages }}"