- name: Create user group
  become: true
  ansible.builtin.group:
    gid: '{{ mattermost_group_gid }}'
    name: '{{ mattermost_group }}'
    state: present

- name: Create user
  become: true
  ansible.builtin.user:
    create_home: no
    group: '{{ mattermost_group }}'
    home: '{{ mattermost_data_dir }}'
    name: '{{ mattermost_user }}'
    password: '{{ lookup("ansible.builtin.password", "/dev/null chars=ascii_lowercase,ascii_uppercase,digits length=40 encrypt=sha512_crypt", seed=sunlab_seed_password) }}'
    shell: '{{ mattermost_user_shell }}'
    state: present
    uid: '{{ mattermost_user_uid }}'

- name: Install packages
  become: true
  pacman:
    name: "{{ item }}"
    state: latest
  with_items: "{{ mattermost_packages }}"