---
- name: Setup database users
  ansible.builtin.include_role:
    name: postgresql
    apply:
      delegate_to: postgres
  vars:
    postgresql_users:
      - name: '{{ mattermost_user }}'
        db: '{{ mattermost_db }}'
        password: supersecure
    postgresql_databases:
      - name: '{{ mattermost_db }}'
        owner: '{{ mattermost_user }}'
