---
- name: Install dependencies
  include_tasks: install.yml

- name: Allow access to SSL certificates
  import_role:
    name: ssl
  vars:
    ssl_users: "{{ mattermost_user }}"
  tags:
    - add-user