---
- name: Setup database users
  ansible.builtin.include_role:
    name: postgresql
    tasks_from: user
    apply:
      delegate_to: postgres
  vars:
    postgresql_users:
      - name: '{{ mattermost_user }}'
        password: supersecure