- name: Include Archlinux OS variables
  ansible.builtin.include_vars: os/Archlinux.yml
  when: ansible_os_family == 'Archlinux'

- name: Include database config variables
  ansible.builtin.include_vars:
    file: 'config/db_{{ mattermost_database_host_type }}.yml'

- name: Include ssl config variables
  ansible.builtin.include_vars:
    file: 'config/ssl_{{ mattermost_ssl }}.yml'

- name: Include service config variables
  ansible.builtin.include_vars:
    file: 'config/service_ssl_{{ mattermost_ssl }}.yml'