- name: Include Archlinux OS variables
  ansible.builtin.include_vars: os/Archlinux.yml
  when: ansible_os_family == 'Archlinux'

- name: Include config variables
  ansible.builtin.include_vars:
    file: 'config/db_{{ mattermost_database_host_type }}.yml'