- name: Copy config template
  become: true
  ansible.builtin.template:
    src: iptables.rules.j2
    dest: '{{ iptables_rules_path }}'
    owner: root
    group: root
    mode: '{{ iptables_rules_file_mode }}'
  register: __iptables_config

# - name: Flush all tables
#   become: true
#   ansible.builtin.iptables:
#     flush: yes
#     table: '{{ item }}'
#   with_items:
#     - filter
#     - nat
#     - mangle
#     - raw
#     - security

- name: Load config
  become: true
  community.general.iptables_state:
    path: '{{ iptables_rules_path }}'
    state: restored
  async: "{{ ansible_timeout }}"
  poll: 0