- name: Copy iptables config template
  become: true
  ansible.builtin.template:
    src: iptables.rules.j2
    dest: '{{ iptables_rules_path }}'
    owner: root
    group: root
    mode: '{{ iptables_rules_file_mode }}'
  register: __iptables_config

- name: Copy ipset config template
  become: true
  ansible.builtin.template:
    src: ipset.conf.j2
    dest: '{{ ipset_config_path }}'
    owner: root
    group: root
    mode: '{{ iptables_rules_file_mode }}'
  register: __ipset_config

- name: Load iptables config
  become: true
  community.general.iptables_state:
    path: '{{ iptables_rules_path }}'
    state: restored
  async: "{{ ansible_timeout }}"
  poll: 0
  when: __iptables_config.changed

- name: Load ipset config
  become: true
  ansible.builtin.command:
    cmd: '{{ ipset_binary | quote }} restore -f {{ ipset_config_path | quote }}'
  when: __ipset_config.changed