- name: Include Archlinux OS variables
  ansible.builtin.include_vars: os/Archlinux.yml
  when: ansible_os_family == 'Archlinux'

- name: Include rule config variables
  ansible.builtin.include_vars:
    file: 'config/rules_{{ iptables_security_level }}.yml'