---
- name: Install aide via apt
  apt:
    name: "{{ aide.apt.install }}"
    state: latest
    install_recommends: no

- name: Check if daily aide cron exists
  stat:
    path: /etc/cron.daily/aide
  register: aidecron

- name: Create aide service
  template:
    src: lib/systemd/system/aidecheck.service.j2
    dest: /lib/systemd/system/aidecheck.service
    mode: 0644
    owner: root
    group: root
  when: not aidecron.stat.exists

- name: Setup aidecheck timer
  template:
    src: lib/systemd/system/aidecheck.timer.j2
    dest: /lib/systemd/system/aidecheck.timer
    mode: 0644
    owner: root
    group: root
  when: not aidecron.stat.exists
  notify:
    - Restart systemd
    - Enable aidecheck

- name: Check if aide.db exists
  stat:
    path: /var/lib/aide/aide.db
  register: aidedb

- name: Initialize aide database
  command: aideinit
  when: not aidedb.stat.exists