---
- name: Install `prowlarr` using yay
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    name: prowlarr
    state: latest
    use: yay

- name: Enable prowlarr service using systemd
  become: yes
  systemd:
    enabled: yes
    name: prowlarr
    state: started