---
- name: Copy authorized_keys
  become: yes
  authorized_key:
    exclusive: yes
    key: "{{ item.key }}"
    state: present
    user: "{{ item.name }}"
  with_items:
    - "{{ config.users.sudo | default([]) }}"

- name: Copy /etc/issue banner
  become: yes
  template:
    src: templates/etc/issue.j2
    dest: /etc/issue
    owner: root
    group: root
    mode: 0600

- name: Copy SSH config
  become: yes
  template:
    src: templates/etc/ssh/sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0600
  notify: Restart sshd

- name: Enable sshd service
  become: yes
  service:
    name: sshd
    enabled: yes
    state: started