# SSL
postgresql_ssl_cert_dir: '{{ certbot_config_live_dir | default("/etc/letsencrypt/live") }}/{{ ansible_hostname }}.{{ sunlab_domain }}'
postgresql_ssl_cert_file: '{{ certbot_cert_file | default("fullchain.pem") }}'
postgresql_ssl_key_file: '{{ certbot_key_file | default("privkey.pem") }}'
postgresql_ssl_group: '{{ certbot_group | default("certbot") }}'
postgresql_ssl_file_mode: 0700

# Config
postgresql_config_ssl:
  - option: ssl
    value: "on"
  - option: ssl_cert_file
    value: "{{ postgresql_data_dir }}/{{ postgresql_ssl_cert_file }}"
  - option: ssl_key_file
    value: "{{ postgresql_data_dir }}/{{ postgresql_ssl_key_file }}"
  - option: ssl_ciphers
    value: "EECDH+AESGCM:EDH+AESGCM"
  - option: ssl_prefer_server_ciphers
    value: "on"
  - option: ssl_ecdh_curve
    value: "secp521r1"
  - option: ssl_min_protocol_version
    value: TLSv1.2